
import {useEffect,useState} from "react";
import {Bot,Check,ChevronRight,Crosshair,Eye,EyeOff,Grid2X2,MessageCircle,RotateCcw,SkipForward,Sparkles,Swords,Trophy,UserRound} from "lucide-react";
import {buildPortrait} from "./personalityData.js";
import {bestDefense,resolveTileBattle,shuffledTiles,strongestCategory,tileCategories} from "./competitiveData.js";
import {shuffle,signs} from "./gameData.js";

const saveBest=(mode,score)=>{let all={};try{all=JSON.parse(localStorage.getItem("zodiac-bests")||"{}")}catch{}if(score>(all[mode]||0)){all[mode]=score;localStorage.setItem("zodiac-bests",JSON.stringify(all));return true}return false};

function GameTop({label,round,total,score,scoreLabel,extra}){return <><div className="game-heading"><div><span className="eyebrow">{label}</span><h1>{total?`Prova ${round} di ${total}`:extra}</h1></div><div className="score-pills"><b>{scoreLabel??`${score} pt`}</b></div></div><div className="progress"><i style={{width:total?`${(round-1)/total*100}%`:"50%"}}/></div></>}
function LocalResult({score,isRecord,onAgain,onExit,title="Partita completata"}){return <main className="page centered"><section className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">{title}</span><h1>{score} punti</h1>{isRecord&&<div className="new-record"><Sparkles/> Nuovo record!</div>}<div className="result-actions"><button className="primary" onClick={onAgain}><RotateCcw/> Rigioca</button><button className="secondary" onClick={onExit}><Grid2X2/> Modalità</button></div></section></main>}
function Signs({onChoose,failed=new Set(),answer=null}){return <div className="sign-picker">{signs.map(s=><button disabled={failed.has(s.name)||!!answer} className={`${failed.has(s.name)?"failed":""} ${answer===s.name?"answer":""}`} onClick={()=>onChoose(s.name)} key={s.name}><strong>{s.symbol}</strong><span>{s.name}</span></button>)}</div>}

export function PersonalityGame({sound,onExit}){
 const total=8,values=[900,680,440,220],makeRounds=()=>shuffle(signs).slice(0,total).map(sign=>({sign,scenes:shuffle(buildPortrait(sign.name))}));
 const[rounds,setRounds]=useState(makeRounds),[round,setRound]=useState(1),[score,setScore]=useState(0),[level,setLevel]=useState(0),[failed,setFailed]=useState(new Set()),[resolved,setResolved]=useState(false),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),current=rounds[round-1];
 function choose(name){if(resolved||failed.has(name))return;if(name===current.sign.name){const nextScore=score+values[level];setScore(nextScore);setResolved(true);sound(true);if(round===total){setIsRecord(saveBest("portrait",nextScore));setDone(true)}}else{sound(false);setFailed(old=>new Set([...old,name]));setLevel(old=>Math.min(3,old+1))}}
 function next(){setRound(old=>old+1);setLevel(0);setFailed(new Set());setResolved(false)}
 function restart(){setRounds(makeRounds());setRound(1);setScore(0);setLevel(0);setFailed(new Set());setResolved(false);setDone(false);setIsRecord(false)}
 if(done)return <LocalResult score={score} isRecord={isRecord} onAgain={restart} onExit={onExit}/>;
 return <main className="page wide-game"><GameTop label="Profilo Vivente" round={round} total={total} score={score}/><section className="portrait-game"><div className="portrait-header"><div><span>264 SCENE · 22 PER SEGNO · IDENTITÀ ANONIMA</span><h2>Osserva ciò che fa, non una lista di aggettivi</h2></div><strong>{values[level]} pt</strong></div><div className="portrait-scenes">{current.scenes.slice(0,level+1).map((scene,index)=><article key={scene.stage}><b>SCENA {index+1} · {scene.stage}</b><p>{scene.text}</p></article>)}</div>{level<3&&!resolved&&<button className="secondary portrait-more" onClick={()=>setLevel(old=>old+1)}>Apri un’altra scena <small>−{values[level]-values[level+1]} pt</small></button>}<Signs onChoose={choose} failed={failed} answer={resolved?current.sign.name:null}/>{resolved&&<div className="portrait-answer"><p><Check/> Il profilo era <b>{current.sign.symbol} {current.sign.name}</b>. Le scene incrociano contesto, relazioni e reazione alla pressione.</p>{round<total&&<button className="primary" onClick={next}>Prossimo fascicolo <ChevronRight/></button>}</div>}</section></main>
}

function TileCard({tile,hidden=false,compact=false,selectedCategory=null,onClick,disabled=false}){
 if(!tile)return null;
 return <button type="button" className={`zodiac-tile ${compact?"compact":""} ${hidden?"hidden-values":""}`} onClick={onClick} disabled={disabled||!onClick}><div className="tile-identity"><strong>{tile.symbol}</strong><span>{tile.name}</span></div>{hidden?<div className="sealed"><EyeOff/> Valori coperti</div>:<><p className="tile-signature">{tile.signature}</p><div className="tile-values">{tileCategories.map(category=><div className={selectedCategory===category.id?"active":""} title={category.description} key={category.id}><span>{category.label}</span><b>{tile.values[category.id]}</b></div>)}</div></>}</button>
}
function TileCounts({leftName="Tu",rightName="CPU",left,right,active,rightBot=true}){const RightIcon=rightBot?Bot:UserRound;return <div className="tile-counts"><div className={active==="left"?"active":""}><UserRound/><span>{leftName}</span><b>{left} tessere</b></div><i>VS</i><div className={active==="right"?"active":""}><RightIcon/><span>{rightName}</span><b>{right} tessere</b></div></div>}

function newCpuMatch(){const deck=shuffledTiles();return{player:deck.slice(0,6),cpu:deck.slice(6),active:Math.random()>.5?"player":"cpu",phase:"category",category:null,last:null,battle:1,winner:null}}
function cpuSecretCategory(tile){const ranked=[...tileCategories].sort((a,b)=>tile.values[b.id]-tile.values[a.id]),roll=Math.random();return ranked[roll<.62?0:roll<.88?1:2].id}
function settleCpu(match,defenseIndex){
 const attackerKey=match.active,defenderKey=attackerKey==="player"?"cpu":"player",attackerDeck=[...match[attackerKey]],defenderDeck=[...match[defenderKey]],attacker=attackerDeck.shift(),defender=defenderDeck.splice(defenseIndex,1)[0],result=resolveTileBattle(attacker,defender,match.category);
 let nextActive;
 if(result.winner==="attacker"){attackerDeck.push(attacker,defender);nextActive=attackerKey}else if(result.winner==="defender"){defenderDeck.push(defender,attacker);nextActive=defenderKey}else{attackerDeck.push(attacker);defenderDeck.push(defender);nextActive=defenderKey}
 const next={...match,[attackerKey]:attackerDeck,[defenderKey]:defenderDeck,active:nextActive,phase:"reveal",last:{attacker,defender,result,category:match.category,attackerKey},battle:match.battle+1};
 if(!attackerDeck.length||!defenderDeck.length)next.winner=attackerDeck.length?attackerKey:defenderKey;
 return next;
}

export function TileCpuGame({sound,onExit}){
 const[match,setMatch]=useState(newCpuMatch),[isRecord,setIsRecord]=useState(false);
 useEffect(()=>{if(match.winner){sound(match.winner==="player");if(match.winner==="player")setIsRecord(saveBest("tilecpu",Math.max(100,6000-(match.battle-1)*40)));return}if(match.phase==="category"&&match.active==="cpu"){const timer=setTimeout(()=>setMatch(old=>({...old,category:cpuSecretCategory(old.cpu[0]),phase:"defense"})),900);return()=>clearTimeout(timer)}if(match.phase==="defense"&&match.active==="player"){const timer=setTimeout(()=>setMatch(old=>settleCpu(old,bestDefense(old.cpu.slice(0,2),strongestCategory(old.player[0])))),1000);return()=>clearTimeout(timer)}if(match.phase==="reveal"){sound(match.last?.result.winner==="tie"?"battle":match.last?.result.winner===(match.last?.attackerKey==="player"?"attacker":"defender"));const timer=setTimeout(()=>setMatch(old=>({...old,phase:"category",category:null,last:null})),2300);return()=>clearTimeout(timer)}},[match.phase,match.active,match.winner]);
 function chooseCategory(category){if(match.phase==="category"&&match.active==="player"){sound("select");setMatch(old=>({...old,category,phase:"defense"}))}}
 function chooseDefense(index){if(match.phase==="defense"&&match.active==="cpu"){sound("select");setMatch(old=>settleCpu(old,index))}}
 if(match.winner)return <main className="page centered"><section className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">DUELLO TERMINATO</span><h1>{match.winner==="player"?"Hai conquistato lo Zodiaco!":"La CPU ha conquistato il mazzo"}</h1>{isRecord&&<div className="new-record"><Sparkles/> Nuovo record strategico</div>}<p>{match.battle-1} scontri giocati.</p><div className="result-actions"><button className="primary" onClick={()=>{setMatch(newCpuMatch());setIsRecord(false)}}><RotateCcw/> Rivincita</button><button className="secondary" onClick={onExit}><Grid2X2/> Modalità</button></div></section></main>;
 const playerActive=match.active==="player",category=tileCategories.find(c=>c.id===match.category);
 return <main className="page tile-page"><GameTop label="Duello delle Tessere · vs CPU" score={Math.max(100,6000-(match.battle-1)*40)} extra={`Scontro ${match.battle}`}/><TileCounts left={match.player.length} right={match.cpu.length} active={playerActive?"left":"right"}/><section className="tile-arena">{match.phase==="category"&&playerActive&&<><div className="tile-instruction"><Swords/><div><b>Sei di mano</b><p>Scegli in segreto una categoria della tua prima tessera. Della CPU puoi vedere soltanto i due segni disponibili.</p></div></div><div className="tile-battle-layout"><TileCard tile={match.player[0]}/><div className="category-picker">{tileCategories.map(c=><button onClick={()=>chooseCategory(c.id)} key={c.id}><span>{c.label}</span><b>{match.player[0].values[c.id]}</b><small>{c.description}</small></button>)}</div><div className="defender-preview">{match.cpu.slice(0,2).map(tile=><TileCard tile={tile} hidden compact key={tile.name}/>)}</div></div></>}{match.phase==="category"&&!playerActive&&<><div className="tile-instruction"><EyeOff/><div><b>La CPU è di mano</b><p>Osserva tutti i valori della sua carta: fra poco sigillerà una categoria senza comunicartela.</p></div></div><div className="secret-defense-layout"><div className="attacker-clue"><span>CARTA DELL’ATTACCANTE</span><TileCard tile={match.cpu[0]}/></div><div className="sealed-category"><Bot/><b>Scelta segreta in corso</b><span>Prepara la tua deduzione.</span></div><div className="defense-choice">{match.player.slice(0,2).map(tile=><TileCard tile={tile} key={tile.name}/>)}</div></div></>}{match.phase==="defense"&&!playerActive&&<><div className="tile-instruction"><EyeOff/><div><b>Categoria sigillata</b><p>La CPU non ti dice cosa ha scelto. Studia la sua carta e scegli quale delle tue due tessere ha più probabilità di contrastarla.</p></div></div><div className="secret-defense-layout"><div className="attacker-clue"><span>CARTA DELL’ATTACCANTE</span><TileCard tile={match.cpu[0]}/></div><div className="sealed-category"><EyeOff/><b>?</b><span>La categoria sarà rivelata soltanto nello scontro.</span></div><div className="defense-choice">{match.player.slice(0,2).map((tile,index)=><TileCard tile={tile} onClick={()=>chooseDefense(index)} key={tile.name}/>)}</div></div></>}{match.phase==="defense"&&playerActive&&<div className="thinking"><Bot/><b>Hai sigillato {category.label}</b><span>La CPU sceglie tra {match.cpu.slice(0,2).map(t=>t.name).join(" e ")} senza conoscere la categoria.</span></div>}{match.phase==="reveal"&&match.last&&<BattleReveal battle={match.last}/>}</section></main>
}

function BattleReveal({battle}){
 const category=tileCategories.find(c=>c.id===battle.category),winner=battle.result.winner;
 return <div className="battle-reveal"><span className="eyebrow">{category.label}</span><div className="revealed-cards"><TileCard tile={battle.attacker} selectedCategory={battle.category}/><div className="versus-burst"><Swords/><b>{battle.result.attack}–{battle.result.defense}</b></div><TileCard tile={battle.defender} selectedCategory={battle.category}/></div><h2>{winner==="tie"?"Pareggio: le tessere tornano ai proprietari":winner==="attacker"?`${battle.attacker.name} conquista lo scontro`:`${battle.defender.name} ribalta lo scontro`}</h2></div>
}

export function TileOnlineMatch({state,session,act,sound,error,onLeave,isHost}){
 const tile=state.tile,me=state.players.find(p=>p.id===session.playerId),opponent=state.players.find(p=>p.id!==session.playerId),amActive=tile.activePlayerId===session.playerId,amDefender=tile.defenderId===session.playerId,category=tileCategories.find(c=>c.id===tile.category);
 useEffect(()=>{if(tile.phase==="reveal"&&tile.lastBattle){const winner=tile.lastBattle.winnerId;sound(winner?winner===session.playerId:"battle")}},[tile.phase,tile.battle]);
 function chooseOnlineCategory(categoryId){sound("select");act("tile-category",{category:categoryId})}
 function chooseOnlineDefense(index){sound("select");act("tile-defense",{index})}
 if(state.status==="finished"){const winner=state.players.find(p=>p.score===12);return <main className="page centered"><section className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">DUELLO TERMINATO</span><h1>{winner?.id===session.playerId?"Hai conquistato lo Zodiaco!":`${winner?.name||"L’avversario"} ha conquistato il mazzo`}</h1><div className="final-scores">{state.players.map(p=><div className={p.id===session.playerId?"me":""} key={p.id}><span>{p.id===winner?.id?"♛":"✦"}</span><b>{p.name}</b><strong>{p.score} tessere</strong></div>)}</div><div className="result-actions">{isHost?<button className="primary" onClick={()=>act("rematch")}><RotateCcw/> Rivincita</button>:<span className="waiting-host">In attesa della rivincita</span>}<button className="secondary" onClick={onLeave}><Grid2X2/> Home · stanza conservata</button></div>{error&&<div className="error">{error}</div>}</section></main>}
 return <main className="page tile-page"><GameTop label="Duello delle Tessere · Online" scoreLabel={`${tile.myCount} tessere`} extra={`Scontro ${tile.battle}`}/><TileCounts leftName={me.name} rightName={opponent.name} left={tile.myCount} right={tile.opponentCount} active={amActive?"left":"right"} rightBot={false}/><section className="tile-arena">{error&&<div className="error">{error}</div>}{tile.phase==="category"&&amActive&&<><div className="tile-instruction"><Swords/><div><b>Sei di mano</b><p>Scegli in segreto la categoria. Dell’avversario conosci soltanto i nomi delle due tessere in cima.</p></div></div><div className="tile-battle-layout"><TileCard tile={tile.myTop[0]}/><div className="category-picker">{tileCategories.map(c=><button onClick={()=>chooseOnlineCategory(c.id)} key={c.id}><span>{c.label}</span><b>{tile.myTop[0].values[c.id]}</b><small>{c.description}</small></button>)}</div><div className="defender-preview">{tile.opponentChoices.map(t=><TileCard tile={t} hidden compact key={t.name}/>)}</div></div></>}{tile.phase==="category"&&!amActive&&<><div className="tile-instruction"><EyeOff/><div><b>{opponent.name} è di mano</b><p>Puoi studiare tutti i valori della sua carta, ma non saprai quale categoria sceglierà.</p></div></div><div className="secret-defense-layout"><div className="attacker-clue"><span>CARTA PUBBLICA DELL’ATTACCANTE</span><TileCard tile={tile.attackerCard}/></div><div className="sealed-category"><Swords/><b>Scelta in corso</b><span>La categoria resterà segreta.</span></div><div className="defense-choice">{tile.myTop.map(t=><TileCard tile={t} key={t.name}/>)}</div></div></>}{tile.phase==="defense"&&amDefender&&<><div className="tile-instruction"><EyeOff/><div><b>{opponent.name} ha sigillato una categoria</b><p>Deduci quale valore potrebbe aver scelto osservando la sua carta, poi schiera una delle tue due tessere.</p></div></div><div className="secret-defense-layout"><div className="attacker-clue"><span>CARTA PUBBLICA DELL’ATTACCANTE</span><TileCard tile={tile.attackerCard}/></div><div className="sealed-category"><EyeOff/><b>?</b><span>Categoria nascosta fino allo scontro</span></div><div className="defense-choice">{tile.myTop.map((t,index)=><TileCard tile={t} onClick={()=>chooseOnlineDefense(index)} key={t.name}/>)}</div></div></>}{tile.phase==="defense"&&!amDefender&&<div className="thinking"><EyeOff/><b>Hai sigillato {category?.label}</b><span>{opponent.name} vede la tua carta ma non la categoria e sta scegliendo tra {tile.opponentChoices.map(t=>t.name).join(" e ")}.</span></div>}{tile.phase==="reveal"&&tile.lastBattle&&<BattleReveal battle={tile.lastBattle}/>}</section></main>
}

const loadGuessBoard=key=>{try{const value=JSON.parse(sessionStorage.getItem(key)||"{}");return{key,excluded:Array.isArray(value.excluded)?value.excluded:[],selected:value.selected||null}}catch{return{key,excluded:[],selected:null}}};

export function GuessWhoOnlineMatch({state,session,act,sound,error,onLeave,isHost}){
 const game=state.guessWho,me=state.players.find(player=>player.id===session.playerId),opponent=state.players.find(player=>player.id!==session.playerId),boardKey=`zodiac-guesswho-${session.code}-${game.matchId}-${session.playerId}`,[board,setBoard]=useState(()=>loadGuessBoard(boardKey)),myTurn=game.turnPlayerId===session.playerId,finished=state.status==="finished",excluded=new Set(board.excluded),selected=board.selected;
 useEffect(()=>{if(board.key!==boardKey)setBoard(loadGuessBoard(boardKey))},[boardKey,board.key]);
 useEffect(()=>{if(board.key===boardKey)sessionStorage.setItem(boardKey,JSON.stringify({excluded:board.excluded,selected:board.selected}))},[board,boardKey]);
 useEffect(()=>{if(game.lastAccusation?.correct)sound(game.winnerId===session.playerId);else if(game.lastAccusation?.playerId===session.playerId)sound(false)},[game.lastAccusation?.playerId,game.lastAccusation?.sign,game.lastAccusation?.correct]);
 function toggle(name){if(finished||!myTurn)return;setBoard(old=>{const next=new Set(old.excluded);next.has(name)?next.delete(name):next.add(name);return{...old,excluded:[...next],selected:next.has(name)&&old.selected===name?null:old.selected}})}
 function pick(name){if(finished||!myTurn||excluded.has(name))return;setBoard(old=>({...old,selected:name}))}
 async function accuse(){if(!selected||!myTurn||finished)return;const result=await act("guesswho-accuse",{sign:selected});if(result&&!result.correct)setBoard(old=>({...old,excluded:[...new Set([...old.excluded,selected])],selected:null}))}
 async function pass(){if(!myTurn||finished)return;sound("select");await act("guesswho-pass")}
 if(finished){const won=game.winnerId===session.playerId;return <main className="page centered"><section className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">INDOVINA CHI · VOCALE</span><h1>{won?"Hai scoperto il segno!":`${opponent.name} ha scoperto il tuo segno`}</h1><div className="guesswho-reveal"><span>Il segno di {opponent.name} era</span><strong>{game.opponentSecret?.symbol} {game.opponentSecret?.name}</strong></div>{error&&<div className="error">{error}</div>}<div className="result-actions">{isHost?<button className="primary" onClick={()=>act("rematch")}><RotateCcw/> Rivincita nella stanza</button>:<span className="waiting-host">In attesa della rivincita</span>}<button className="secondary" onClick={onLeave}><Grid2X2/> Home · stanza conservata</button></div></section></main>}
 const lastPlayer=state.players.find(player=>player.id===game.lastAccusation?.playerId);
 return <main className="page wide-game"><GameTop label="Indovina Chi · Online vocale" scoreLabel={`${12-excluded.size} possibili`} extra={myTurn?"È il tuo turno":"Turno dell’avversario"}/><section className="online-guesswho"><div className="voice-secret"><span>LA TUA IDENTITÀ SEGRETA</span><strong>{game.mySecret?.symbol}</strong><h2>{game.mySecret?.name}</h2><p>Rispondi a voce alle domande di {opponent.name} senza mostrare questa carta.</p></div><div className="voice-board"><div className={`turn-banner ${myTurn?"mine":"theirs"}`}><MessageCircle/><div><b>{myTurn?`Fai una domanda a voce a ${opponent.name}`:`Ascolta ${opponent.name} e rispondi a voce`}</b><span>{myTurn?"Dopo la risposta, aggiorna manualmente il tuo tabellone. L’app non propone domande.":`Rispondi pensando soltanto alla tua identità: ${game.mySecret?.name}.`}</span></div></div>{game.lastAccusation&&!game.lastAccusation.correct&&<div className="wrong-accusation">{lastPlayer?.name} ha accusato {game.lastAccusation.sign}: identità errata, turno passato.</div>}<div className="guess-board voice-mode">{signs.map(sign=>{const isExcluded=excluded.has(sign.name);return <article className={`${isExcluded?"excluded":""} ${selected===sign.name?"selected":""}`} key={sign.name}><button className="suspect" disabled={!myTurn||isExcluded} onClick={()=>pick(sign.name)}><strong>{sign.symbol}</strong><span>{sign.name}</span></button><button className={`eliminate ${isExcluded?"restore":""}`} disabled={!myTurn} onClick={()=>toggle(sign.name)}>{isExcluded?<Eye/>:<EyeOff/>}<span>{isExcluded?"ESCLUSO":"POSSIBILE"}</span></button></article>})}</div><div className="accuse-bar voice-actions">{myTurn?<><p>{selected?<>Vuoi accusare <b>{selected}</b>?</>:"Fai la domanda a voce, aggiorna i possibili e poi accusa o passa."}</p><div><button className="secondary" onClick={pass}><SkipForward/> Passa il turno</button><button className="primary" disabled={!selected} onClick={accuse}><Crosshair/> Accusa</button></div></>:<p><Eye/> Il tabellone è fermo finché {opponent.name} non conclude il turno.</p>}</div>{error&&<div className="error">{error}</div>}</div></section></main>
}
