import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowLeft,BookOpen,CalendarDays,Check,ChevronRight,Clock3,Copy,Flame,Gamepad2,Globe2,Grid2X2,HelpCircle,Home as HomeIcon,Link2,LoaderCircle,Medal,Orbit,Play,RotateCcw,Settings,Share2,Sparkles,Timer,Trophy,UserRound,UsersRound,Volume2,VolumeX,X,Zap} from "lucide-react";
import {makeQuestion,modeInfo,onlineModes,soloModes} from "./gameData.js";

const modeIcons={identikit:HelpCircle,calendar:CalendarDays,element:Grid2X2,truefalse:Zap,intruder:Flame,symbol:Sparkles,planet:Orbit,mixed:Gamepad2,blitz:Timer};
const modeColors={identikit:"#a78bfa",calendar:"#60a5fa",element:"#34d399",truefalse:"#fbbf24",intruder:"#fb7185",symbol:"#f472b6",planet:"#818cf8",mixed:"#ffc857",blitz:"#22d3ee"};
const api=async(path,data)=>{const r=await fetch(path,{method:data?"POST":"GET",headers:data?{"content-type":"application/json"}:{},body:data?JSON.stringify(data):undefined});const value=await r.json().catch(()=>({}));if(!r.ok)throw new Error(value.error||"Connessione non riuscita.");return value};

export default function App(){
 const[screen,setScreen]=useState("home"),[soloMode,setSoloMode]=useState("mixed"),[sound,setSound]=useState(()=>localStorage.getItem("zodiac-sound")!=="off"),[rules,setRules]=useState(false),[session,setSession]=useState(null),[onlineState,setOnlineState]=useState(null),[connection,setConnection]=useState("online");
 useEffect(()=>localStorage.setItem("zodiac-sound",sound?"on":"off"),[sound]);
 useEffect(()=>{if(!session)return;sessionStorage.setItem("zodiac-session",JSON.stringify(session));let source;
  const connect=()=>{source=new EventSource(`/api/events?code=${encodeURIComponent(session.code)}&playerId=${encodeURIComponent(session.playerId)}&token=${encodeURIComponent(session.token)}`);source.onopen=()=>setConnection("online");source.onmessage=e=>{setOnlineState(JSON.parse(e.data));setConnection("online")};source.onerror=()=>setConnection("reconnecting")};connect();return()=>source?.close()},[session]);
 function tone(ok=true){if(!sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?660:190;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.16);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.16)}catch{}}
 function goHome(){setScreen("home");setSession(null);setOnlineState(null);sessionStorage.removeItem("zodiac-session")}
 return <div className="app-shell"><Stars/><Topbar screen={screen} onBack={()=>screen==="solo"?setScreen("soloModes"):screen==="online"?goHome():setScreen("home")} sound={sound} setSound={setSound} openRules={()=>setRules(true)} connection={screen==="online"?connection:null}/>
  {screen==="home"&&<Home onSolo={()=>setScreen("soloModes")} onOnline={()=>setScreen("onlineSetup")} onReconnect={()=>{try{const s=JSON.parse(sessionStorage.getItem("zodiac-session"));if(s){setSession(s);setScreen("online")}}catch{}}}/>} 
  {screen==="soloModes"&&<ModeMenu onChoose={m=>{setSoloMode(m);setScreen("solo")}}/>}
  {screen==="solo"&&<SoloGame mode={soloMode} sound={tone} onExit={()=>setScreen("soloModes")}/>}
  {screen==="onlineSetup"&&<OnlineSetup onReady={s=>{setSession(s);setOnlineState(s.state);setScreen("online")}}/>}
  {screen==="online"&&<OnlineRoom session={session} state={onlineState} sound={tone} onLeave={goHome}/>} {rules&&<Rules onClose={()=>setRules(false)}/>}</div>
}

function Stars(){return <div className="stars" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div>}
function Topbar({screen,onBack,sound,setSound,openRules,connection}){return <header className="topbar"><div>{screen!=="home"&&<button className="icon-text" onClick={onBack}><ArrowLeft size={18}/> Indietro</button>}</div><div className="brand-mini"><span>✦</span> ZODIACO ARENA</div><div className="top-actions">{connection&&<span className={`connection ${connection}`}>{connection==="online"?"Online":"Riconnessione…"}</span>}<button className="icon-button" onClick={()=>setSound(!sound)} aria-label={sound?"Disattiva suoni":"Attiva suoni"}>{sound?<Volume2/>:<VolumeX/>}</button><button className="icon-button" onClick={openRules} aria-label="Regole"><BookOpen/></button></div></header>}

function Home({onSolo,onOnline,onReconnect}){const hasSession=!!sessionStorage.getItem("zodiac-session");return <main className="page home-page"><section className="hero"><div className="eyebrow"><Sparkles size={15}/> IL QUIZ DELLE STELLE</div><h1>Quanto conosci<br/><em>lo Zodiaco?</em></h1><p>Scegli la tua sfida: allenati da solo oppure affronta un’altra persona in tempo reale.</p></section><section className="play-choices"><button className="play-card solo" onClick={onSolo}><div className="card-icon"><UserRound/></div><div><small>ALLENAMENTO</small><h2>Giocatore singolo</h2><p>Nove modalità, record personali e serie di risposte esatte.</p></div><ChevronRight/></button><button className="play-card online" onClick={onOnline}><div className="live-pill">● LIVE</div><div className="card-icon"><UsersRound/></div><div><small>SFIDA ONLINE</small><h2>Due giocatori</h2><p>Crea una stanza privata e manda il codice al tuo avversario.</p></div><ChevronRight/></button></section>{hasSession&&<button className="resume" onClick={onReconnect}><Link2 size={17}/> Rientra nell’ultima stanza</button>}<div className="feature-row"><span><Zap/> Punti velocità</span><span><Trophy/> Record salvati</span><span><Globe2/> Online in tempo reale</span></div></main>}

function ModeMenu({onChoose}){return <main className="page"><section className="section-heading"><div><span className="eyebrow"><UserRound size={15}/> GIOCATORE SINGOLO</span><h1>Scegli la modalità</h1><p>Ogni partita normale dura 10 domande. Nel Blitz hai 60 secondi.</p></div></section><div className="mode-grid">{soloModes.map((m,i)=>{const Icon=modeIcons[m],best=readBest(m);return <button className="mode-card" onClick={()=>onChoose(m)} key={m} style={{"--mode":modeColors[m]}}><div className="mode-top"><span className="mode-icon"><Icon/></span><span className="mode-number">0{i+1}</span></div><h2>{modeInfo[m].title}</h2><p>{modeInfo[m].description}</p><footer>{best?<span><Medal size={15}/> Record {best}</span>:<span>Mai giocata</span>}<ChevronRight/></footer></button>})}</div></main>}

function readBest(mode){try{return JSON.parse(localStorage.getItem("zodiac-bests")||"{}")[mode]||0}catch{return 0}}
function saveBest(mode,score){let all={};try{all=JSON.parse(localStorage.getItem("zodiac-bests")||"{}")}catch{}if(score>(all[mode]||0)){all[mode]=score;localStorage.setItem("zodiac-bests",JSON.stringify(all));return true}return false}

function SoloGame({mode,sound,onExit}){const[q,setQ]=useState(()=>makeQuestion(mode)),[round,setRound]=useState(1),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[choice,setChoice]=useState(null),[time,setTime]=useState(60),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false);const total=10,isBlitz=mode==="blitz";
 useEffect(()=>{if(!isBlitz||done)return;const t=setInterval(()=>setTime(v=>{if(v<=1){setDone(true);return 0}return v-1}),1000);return()=>clearInterval(t)},[isBlitz,done]);
 useEffect(()=>{if(done)setIsRecord(saveBest(mode,score))},[done,mode,score]);
 function choose(value){if(choice||done)return;setChoice(value);const ok=value===q.answer;sound(ok);if(ok){setScore(s=>s+100+Math.min(streak,5)*20);setStreak(s=>s+1)}else setStreak(0);if(isBlitz)setTimeout(()=>next(),450)}
 function next(){if(!isBlitz&&round>=total){setDone(true);return}setRound(r=>r+1);setChoice(null);setQ(makeQuestion(mode))}
 function restart(){setQ(makeQuestion(mode));setRound(1);setScore(0);setStreak(0);setChoice(null);setTime(60);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest(mode),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page game-page"><GameHeading label={modeInfo[mode].title} round={isBlitz?null:round} total={total} time={isBlitz?time:null} score={score} streak={streak}/><QuestionCard question={q} choice={choice} onChoose={choose} revealed={!!choice} onNext={isBlitz?null:next}/></main>}

function GameHeading({label,round,total,time,score,streak,children}){return <><div className="game-heading"><div><span className="eyebrow">{label}</span><h1>{time!=null?`${time} secondi`:`Domanda ${round} di ${total}`}</h1></div><div className="score-pills"><span>🔥 {streak||0}</span><b>{score} pt</b></div></div>{children}<div className="progress"><i style={{width:`${time!=null?time/60*100:(round-1)/total*100}%`}}/></div></>}

function QuestionCard({question,choice,onChoose,revealed,onNext,disabled=false,playerAnswers=null}){return <section className="question-card"><div className="question-symbol">{question.symbol}</div><span className="question-kind">{modeInfo[question.mode]?.title}</span><h2>{question.prompt}</h2><div className="answer-grid">{question.options.map(option=>{let state="";if(revealed)state=option===question.answer?"correct":option===choice?"wrong":"muted";return <button key={option} disabled={disabled||!!choice} onClick={()=>onChoose(option)} className={state}><span>{option}</span>{state==="correct"?<Check/>:state==="wrong"?<X/>:null}{playerAnswers&&<small>{playerAnswers.filter(a=>a.choice===option).map(a=>a.name).join(" · ")}</small>}</button>})}</div>{revealed&&question.explanation&&<div className="explanation"><p><b>{choice===question.answer?"Esatto!":"Risposta corretta: "+question.answer}</b> {question.explanation}</p>{onNext&&<button className="primary small" onClick={onNext}>Prossima <ChevronRight/></button>}</div>}</section>}

function OnlineSetup({onReady}){const[tab,setTab]=useState("create"),[name,setName]=useState(""),[roomCode,setRoomCode]=useState(""),[mode,setMode]=useState("mixed"),[rounds,setRounds]=useState(10),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e){e.preventDefault();setBusy(true);setError("");try{const s=tab==="create"?await api("/api/rooms",{name,mode,rounds}):await api(`/api/rooms/${roomCode.trim().toUpperCase()}/join`,{name});onReady(s)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main className="page setup-page"><section className="setup-card"><div className="setup-title"><span className="card-icon"><UsersRound/></span><div><span className="eyebrow">DUE GIOCATORI</span><h1>Partita online</h1></div></div><div className="tabs"><button className={tab==="create"?"active":""} onClick={()=>setTab("create")}>Crea stanza</button><button className={tab==="join"?"active":""} onClick={()=>setTab("join")}>Entra con codice</button></div><form onSubmit={submit}><label>Il tuo nome<input value={name} maxLength={18} onChange={e=>setName(e.target.value)} placeholder="Es. Mattia" autoComplete="nickname" required minLength={2}/></label>{tab==="create"?<><label>Tipo di sfida<select value={mode} onChange={e=>setMode(e.target.value)}>{onlineModes.map(m=><option value={m} key={m}>{modeInfo[m].title}</option>)}</select></label><fieldset><legend>Numero di domande</legend><div className="segmented">{[5,10,15].map(n=><button type="button" className={rounds===n?"active":""} onClick={()=>setRounds(n)} key={n}>{n}</button>)}</div></fieldset></>:<label>Codice stanza<input className="code-input" value={roomCode} maxLength={5} onChange={e=>setRoomCode(e.target.value.toUpperCase())} placeholder="ABCDE" required/></label>}{error&&<div className="error"><X/> {error}</div>}<button className="primary wide" disabled={busy}>{busy?<><LoaderCircle className="spin"/> Collegamento…</>:tab==="create"?<><Play/> Crea la stanza</>:<><Link2/> Entra nella stanza</>}</button></form><p className="privacy-note">Le stanze sono private e si aprono solo conoscendo il codice.</p></section></main>}

function OnlineRoom({session,state,sound,onLeave}){const[localChoice,setLocalChoice]=useState(null),[error,setError]=useState(""),[copied,setCopied]=useState(false),[left,setLeft]=useState(20),lastQuestion=useRef(null);const me=state?.players?.find(p=>p.id===session?.playerId),isHost=state?.hostId===session?.playerId;
 useEffect(()=>{if(!state?.question)return;if(lastQuestion.current!==state.question.id){lastQuestion.current=state.question.id;setLocalChoice(null)}},[state?.question]);
 useEffect(()=>{if(state?.status!=="playing"||!state.roundEndsAt)return;const tick=()=>setLeft(Math.max(0,Math.ceil((state.roundEndsAt-Date.now())/1000)));tick();const t=setInterval(tick,250);return()=>clearInterval(t)},[state?.status,state?.roundEndsAt,state?.question?.id]);
 useEffect(()=>{const mine=state?.status==="reveal"?state.answers?.[session?.playerId]:null;if(mine)sound(mine.correct)},[state?.status,state?.question?.id]);
 async function act(action,data={}){setError("");try{return await api(`/api/rooms/${session.code}/${action}`,{playerId:session.playerId,token:session.token,...data})}catch(e){setError(e.message)}}
 async function choose(choice){if(localChoice)return;setLocalChoice(choice);await act("answer",{choice})}
 async function copy(){await navigator.clipboard.writeText(session.code);setCopied(true);setTimeout(()=>setCopied(false),1500)}
 if(!state)return <main className="page centered"><LoaderCircle className="spin big"/><p>Collegamento alla stanza…</p></main>;
 if(state.status==="lobby")return <main className="page lobby-page"><section className="lobby-card"><span className="eyebrow"><Globe2/> STANZA PRIVATA</span><h1>Invita il secondo giocatore</h1><p>Condividi questo codice. La partita inizierà appena sarete entrambi pronti.</p><button className="room-code" onClick={copy}><span>{session.code}</span><small>{copied?<><Check/> Copiato</>:<><Copy/> Copia codice</>}</small></button><div className="players">{state.players.map((p,i)=><Player key={p.id} player={p} host={p.id===state.hostId} index={i}/>)}{state.players.length<2&&<div className="player waiting"><LoaderCircle className="spin"/><div><b>In attesa…</b><small>Il posto è libero</small></div></div>}</div><div className="lobby-settings"><span>{modeInfo[state.settings.mode].title}</span><i/> <span>{state.settings.rounds} domande</span><i/> <span>20 secondi</span></div>{error&&<div className="error"><X/> {error}</div>}{isHost?<button className="primary wide" disabled={state.players.length<2} onClick={()=>act("start")}><Play/> {state.players.length<2?"Attendi il secondo giocatore":"Inizia la sfida"}</button>:<div className="waiting-host"><LoaderCircle className="spin"/> Chi ha creato la stanza avvierà la partita</div>}<button className="text-button" onClick={onLeave}>Esci dalla stanza</button></section></main>;
 if(state.status==="finished"){const sorted=[...state.players].sort((a,b)=>b.score-a.score),winner=sorted[0].score===sorted[1].score?null:sorted[0];return <main className="page centered"><section className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">PARTITA TERMINATA</span><h1>{winner?`${winner.name} vince!`:"Pareggio perfetto!"}</h1><div className="final-scores">{sorted.map((p,i)=><div className={p.id===session.playerId?"me":""} key={p.id}><span>{i===0?"🥇":"🥈"}</span><b>{p.name}</b><strong>{p.score} pt</strong></div>)}</div>{error&&<div className="error"><X/> {error}</div>}<div className="result-actions">{isHost?<button className="primary" onClick={()=>act("rematch")}><RotateCcw/> Rivincita</button>:<div className="waiting-host"><LoaderCircle className="spin"/> In attesa della rivincita</div>}<button className="secondary" onClick={onLeave}><HomeIcon/> Menu</button></div></section></main>}
 const revealed=state.status==="reveal",answerEntries=revealed?Object.entries(state.answers).map(([id,a])=>({...a,name:state.players.find(p=>p.id===id)?.name||"Giocatore"})):[];
 return <main className="page game-page"><GameHeading label={`${modeInfo[state.settings.mode].title} · Online`} round={state.round} total={state.settings.rounds} score={me?.score||0} streak={0}><div className="versus-bar">{state.players.map(p=><div key={p.id} className={p.id===session.playerId?"me":""}><span className={p.connected?"dot on":"dot"}/><b>{p.name}</b><strong>{p.score}</strong></div>)}<span className="versus">VS</span><div className="round-clock"><Clock3/> {revealed?"Risultato":`${left}s`}</div></div></GameHeading>{error&&<div className="error"><X/> {error}</div>}<QuestionCard question={state.question} choice={localChoice} onChoose={choose} revealed={revealed} disabled={state.answeredPlayerIds?.includes(session.playerId)} playerAnswers={answerEntries}/>{!revealed&&localChoice&&<div className="answer-wait"><Check/> Risposta inviata. Aspettiamo l’altro giocatore…</div>}</main>}

function Player({player,host,index}){return <div className="player"><div className={`avatar a${index}`}>{player.name.slice(0,1).toUpperCase()}</div><div><b>{player.name} {host&&<span>HOST</span>}</b><small>{player.connected?"Connesso":"Connessione persa"}</small></div><i className={player.connected?"online-dot":""}/></div>}
function Result({score,best,isRecord,onAgain,onHome}){return <main className="page centered"><section className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">PARTITA COMPLETATA</span><h1>{score} punti</h1>{isRecord&&<div className="new-record"><Sparkles/> Nuovo record!</div>}<p>Record personale: <b>{best} punti</b></p><div className="result-actions"><button className="primary" onClick={onAgain}><RotateCcw/> Rigioca</button><button className="secondary" onClick={onHome}><Grid2X2/> Modalità</button></div></section></main>}
function Rules({onClose}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="rules-title"><button className="modal-close" onClick={onClose}><X/></button><span className="eyebrow">COME SI GIOCA</span><h2 id="rules-title">Regole rapide</h2><div className="rule-list"><div><b>Solo</b><p>Rispondi a 10 domande. Guadagni 100 punti più un bonus serie fino a 100 punti.</p></div><div><b>Blitz</b><p>Hai 60 secondi: dopo ogni risposta la domanda cambia automaticamente.</p></div><div><b>Online</b><p>Condividi il codice con una persona. Avete la stessa domanda e 20 secondi per rispondere.</p></div><div><b>Punti online</b><p>Una risposta esatta vale 100 punti, più fino a 50 punti in base alla velocità.</p></div></div><button className="primary wide" onClick={onClose}>Ho capito</button></section></div>}
