import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowLeft,BookOpen,Check,ChevronRight,Clock3,Copy,Crosshair,Eye,EyeOff,FileSearch,Gamepad2,Globe2,Grid2X2,Home as HomeIcon,Link2,LoaderCircle,Medal,Orbit,Play,RotateCcw,Sparkles,Target,Timer,Trophy,Undo2,UserRound,UsersRound,Volume2,VolumeX,X,Zap} from "lucide-react";
import {buildQuestionSet,expertStatements,makeQuestion,modeInfo,onlineModes,pick,progressiveClues,shuffle,signs,soloModes} from "./gameData.js";

const modeIcons={guesswho:Eye,clues:FileSearch,constellation:Orbit,order:Undo2,dossier:Crosshair,expert:BookOpen,logic:Target,mixed:Gamepad2,blitz:Timer};
const modeColors={guesswho:"#a78bfa",clues:"#60a5fa",constellation:"#22d3ee",order:"#34d399",dossier:"#f472b6",expert:"#fb7185",logic:"#818cf8",mixed:"#ffc857",blitz:"#f59e0b"};
const api=async(path,data)=>{const r=await fetch(path,{method:data?"POST":"GET",headers:data?{"content-type":"application/json"}:{},body:data?JSON.stringify(data):undefined});const value=await r.json().catch(()=>({}));if(!r.ok)throw new Error(value.error||"Connessione non riuscita.");return value};

export default function App(){
 const[screen,setScreen]=useState("home"),[soloMode,setSoloMode]=useState("mixed"),[sound,setSound]=useState(()=>localStorage.getItem("zodiac-sound")!=="off"),[rules,setRules]=useState(false),[session,setSession]=useState(null),[onlineState,setOnlineState]=useState(null),[connection,setConnection]=useState("online");
 useEffect(()=>localStorage.setItem("zodiac-sound",sound?"on":"off"),[sound]);
 useEffect(()=>{if(!session)return;sessionStorage.setItem("zodiac-session",JSON.stringify(session));let source;
  const connect=()=>{source=new EventSource(`/api/events?code=${encodeURIComponent(session.code)}&playerId=${encodeURIComponent(session.playerId)}&token=${encodeURIComponent(session.token)}`);source.onopen=()=>setConnection("online");source.onmessage=e=>{setOnlineState(JSON.parse(e.data));setConnection("online")};source.onerror=()=>setConnection("reconnecting")};connect();return()=>source?.close()},[session]);
 function tone(ok=true){if(!sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?660:190;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.16);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.16)}catch{}}
 function goHome(){setScreen("home");setSession(null);setOnlineState(null);sessionStorage.removeItem("zodiac-session")}
 return <div className="app-shell"><Stars/><Topbar screen={screen} onBack={()=>screen==="solo"?setScreen("soloModes"):screen==="online"?goHome():setScreen("home")} sound={sound} setSound={setSound} openRules={()=>setRules(true)} connection={screen==="online"?connection:null}/>
  {screen==="home"&&<Home onSolo={()=>setScreen("soloModes")} onOnline={()=>setScreen("onlineSetup")} onReconnect={()=>{try{const s=JSON.parse(sessionStorage.getItem("zodiac-session"));if(s){setSession(s);setScreen("online")}}catch{}}}/>} 
  {screen==="soloModes"&&<ModeMenu onChoose={m=>{setSoloMode(m);setScreen("solo")}}/>}
  {screen==="solo"&&<SoloGame mode={soloMode} sound={tone} onExit={()=>setScreen("soloModes")}/>}
  {screen==="onlineSetup"&&<OnlineSetup onReady={s=>{setSession(s);setOnlineState(s.state);setScreen("online")}}/>}
  {screen==="online"&&<OnlineRoom session={session} state={onlineState} sound={tone} onLeave={goHome}/>} {rules&&<Rules onClose={()=>setRules(false)}/>}</div>
}

function Stars(){return <div className="stars" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div>}
function Topbar({screen,onBack,sound,setSound,openRules,connection}){return <header className="topbar"><div>{screen!=="home"&&<button className="icon-text" onClick={onBack}><ArrowLeft size={18}/> Indietro</button>}</div><div className="brand-mini"><span>✦</span> ZODIACO ARENA</div><div className="top-actions">{connection&&<span className={`connection ${connection}`}>{connection==="online"?"Online":"Riconnessione…"}</span>}<button className="icon-button" onClick={()=>setSound(!sound)} aria-label={sound?"Disattiva suoni":"Attiva suoni"}>{sound?<Volume2/>:<VolumeX/>}</button><button className="icon-button" onClick={openRules} aria-label="Regole"><BookOpen/></button></div></header>}

function Home({onSolo,onOnline,onReconnect}){const hasSession=!!sessionStorage.getItem("zodiac-session");return <main className="page home-page"><section className="hero"><div className="eyebrow"><Sparkles size={15}/> IL QUIZ DELLE STELLE</div><h1>Quanto conosci<br/><em>lo Zodiaco?</em></h1><p>Scegli la tua sfida: allenati da solo oppure affronta un’altra persona in tempo reale.</p></section><section className="play-choices"><button className="play-card solo" onClick={onSolo}><div className="card-icon"><UserRound/></div><div><small>ALLENAMENTO</small><h2>Giocatore singolo</h2><p>Nove modalità, record personali e serie di risposte esatte.</p></div><ChevronRight/></button><button className="play-card online" onClick={onOnline}><div className="live-pill">● LIVE</div><div className="card-icon"><UsersRound/></div><div><small>SFIDA ONLINE</small><h2>Due giocatori</h2><p>Crea una stanza privata e manda il codice al tuo avversario.</p></div><ChevronRight/></button></section>{hasSession&&<button className="resume" onClick={onReconnect}><Link2 size={17}/> Rientra nell’ultima stanza</button>}<div className="feature-row"><span><Zap/> Punti velocità</span><span><Trophy/> Record salvati</span><span><Globe2/> Online in tempo reale</span></div></main>}

function ModeMenu({onChoose}){return <main className="page"><section className="section-heading"><div><span className="eyebrow"><UserRound size={15}/> LIVELLO ESPERTO</span><h1>Scegli la modalità</h1><p>Prove di deduzione, memoria e strategia. Le domande non si ripetono nella stessa partita.</p></div></section><div className="mode-grid">{soloModes.map((m,i)=>{const Icon=modeIcons[m],best=readBest(m);return <button className="mode-card" onClick={()=>onChoose(m)} key={m} style={{"--mode":modeColors[m]}}><div className="mode-top"><span className="mode-icon"><Icon/></span><span className="mode-number">0{i+1}</span></div><h2>{modeInfo[m].title}</h2><p>{modeInfo[m].description}</p><footer>{best?<span><Medal size={15}/> Record {best}</span>:<span>Mai giocata</span>}<ChevronRight/></footer></button>})}</div></main>}

function readBest(mode){try{return JSON.parse(localStorage.getItem("zodiac-bests")||"{}")[mode]||0}catch{return 0}}
function saveBest(mode,score){let all={};try{all=JSON.parse(localStorage.getItem("zodiac-bests")||"{}")}catch{}if(score>(all[mode]||0)){all[mode]=score;localStorage.setItem("zodiac-bests",JSON.stringify(all));return true}return false}

function SoloGame(props){if(props.mode==="guesswho")return <GuessWhoGame {...props}/>;if(props.mode==="clues")return <ClueGame {...props}/>;if(props.mode==="constellation")return <ConstellationGame {...props}/>;if(props.mode==="order")return <OrderGame {...props}/>;if(props.mode==="dossier")return <DossierGame {...props}/>;if(props.mode==="expert")return <ExpertGame {...props}/>;return <ClassicGame {...props}/>}

function ClassicGame({mode,sound,onExit}){const isBlitz=mode==="blitz",total=isBlitz?40:10;const[deck,setDeck]=useState(()=>buildQuestionSet(isBlitz?"mixed":mode,total)),[round,setRound]=useState(1),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[choice,setChoice]=useState(null),[time,setTime]=useState(60),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),q=deck[Math.min(round-1,deck.length-1)];
 useEffect(()=>{if(!isBlitz||done)return;const t=setInterval(()=>setTime(v=>{if(v<=1){setDone(true);return 0}return v-1}),1000);return()=>clearInterval(t)},[isBlitz,done]);
 useEffect(()=>{if(done)setIsRecord(saveBest(mode,score))},[done,mode,score]);
 function choose(value){if(choice||done)return;setChoice(value);const ok=value===q.answer;sound(ok);if(ok){setScore(s=>s+140+Math.min(streak,5)*25);setStreak(s=>s+1)}else setStreak(0);if(isBlitz)setTimeout(next,380)}
 function next(){if(round>=total){setDone(true);return}setRound(r=>r+1);setChoice(null)}
 function restart(){setDeck(buildQuestionSet(isBlitz?"mixed":mode,total));setRound(1);setScore(0);setStreak(0);setChoice(null);setTime(60);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest(mode),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page game-page"><GameHeading label={modeInfo[mode].title} round={isBlitz?null:round} total={total} time={isBlitz?time:null} score={score} streak={streak}/><QuestionCard question={q} choice={choice} onChoose={choose} revealed={!!choice} onNext={isBlitz?null:next}/></main>}

function GuessWhoGame({sound,onExit}){const total=5;const[targets,setTargets]=useState(()=>shuffle(signs).slice(0,total)),[round,setRound]=useState(1),[score,setScore]=useState(0),[shown,setShown]=useState(1),[wrong,setWrong]=useState(0),[excluded,setExcluded]=useState(new Set()),[selected,setSelected]=useState(null),[resolved,setResolved]=useState(null),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),target=targets[round-1],clues=progressiveClues(target);
 function accuse(){if(!selected||resolved)return;if(selected===target.name){const points=Math.max(100,700-(shown-1)*100-wrong*120),nextScore=score+points;sound(true);setScore(nextScore);setResolved(points);if(round===total){setIsRecord(saveBest("guesswho",nextScore));setDone(true)}}else{sound(false);setWrong(v=>v+1);setExcluded(s=>new Set([...s,selected]));setSelected(null);setShown(v=>Math.min(clues.length,v+1))}}
 function next(){setRound(v=>v+1);setShown(1);setWrong(0);setExcluded(new Set());setSelected(null);setResolved(null)}
 function restart(){setTargets(shuffle(signs).slice(0,total));setRound(1);setScore(0);setShown(1);setWrong(0);setExcluded(new Set());setSelected(null);setResolved(null);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("guesswho"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page wide-game"><GameHeading label="Indovina Chi" round={round} total={total} score={score}/><section className="detective-panel"><div className="clue-stack"><span>INDIZI APERTI · {shown}/6</span>{clues.slice(0,shown).map((c,i)=><p key={c}><b>{i+1}</b>{c}</p>)}{shown<clues.length&&!resolved&&<button className="secondary" onClick={()=>setShown(v=>v+1)}><Eye/> Apri un altro indizio <small>−100 pt</small></button>}</div><div className="guess-board">{signs.map(s=><article className={`${excluded.has(s.name)?"excluded":""} ${selected===s.name?"selected":""} ${resolved&&s.name===target.name?"correct":""}`} key={s.name}><button className="suspect" disabled={excluded.has(s.name)||!!resolved} onClick={()=>setSelected(s.name)}><strong>{s.symbol}</strong><span>{s.name}</span></button><button className="eliminate" disabled={!!resolved} onClick={()=>setExcluded(old=>{const n=new Set(old);n.has(s.name)?n.delete(s.name):n.add(s.name);return n})}>{excluded.has(s.name)?<Eye/>:<EyeOff/>}</button></article>)}</div><div className="accuse-bar">{resolved?<><p><Check/> Identità scoperta: <b>{target.name}</b> · +{resolved} punti</p>{round<total&&<button className="primary" onClick={next}>Prossimo caso <ChevronRight/></button>}</>:<><p>{selected?<>Sospetti che sia <b>{selected}</b>?</>:"Seleziona un sospetto, elimina gli altri e formula l’accusa."}</p><button className="primary" disabled={!selected} onClick={accuse}><Crosshair/> Accusa</button></>}</div></section></main>}

function ClueGame({sound,onExit}){const total=6,values=[650,500,360,240,150,80];const[targets,setTargets]=useState(()=>shuffle(signs).slice(0,total)),[round,setRound]=useState(1),[score,setScore]=useState(0),[level,setLevel]=useState(0),[failed,setFailed]=useState(new Set()),[resolved,setResolved]=useState(false),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),target=targets[round-1],clues=progressiveClues(target);
 function choose(name){if(resolved||failed.has(name))return;if(name===target.name){const nextScore=score+values[level];setScore(nextScore);setResolved(true);sound(true);if(round===total){setIsRecord(saveBest("clues",nextScore));setDone(true)}}else{sound(false);setFailed(s=>new Set([...s,name]));setLevel(v=>Math.min(5,v+1))}}
 function next(){setRound(v=>v+1);setLevel(0);setFailed(new Set());setResolved(false)}function restart(){setTargets(shuffle(signs).slice(0,total));setRound(1);setScore(0);setLevel(0);setFailed(new Set());setResolved(false);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("clues"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page wide-game"><GameHeading label="Rivelazione" round={round} total={total} score={score}/><section className="revelation"><div className="value-orbit"><span>VALORE INDIZIO</span><strong>{values[level]}</strong><small>punti</small></div><div className="active-clue"><small>INDIZIO {level+1} DI 6</small><h2>{clues[level]}</h2><div className="clue-dots">{clues.map((_,i)=><i className={i<=level?"on":""} key={i}/>)}</div></div><SignPicker onChoose={choose} failed={failed} answer={resolved?target.name:null}/>{resolved&&round<total&&<button className="primary next-round" onClick={next}>Continua <ChevronRight/></button>}</section></main>}

function ConstellationGame({sound,onExit}){const total=6;const[targets,setTargets]=useState(()=>shuffle(signs).slice(0,total)),[round,setRound]=useState(1),[score,setScore]=useState(0),[lines,setLines]=useState(false),[failed,setFailed]=useState(new Set()),[resolved,setResolved]=useState(false),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),target=targets[round-1];
 function choose(name){if(resolved||failed.has(name))return;if(name===target.name){const points=Math.max(100,(lines?350:600)-failed.size*100),nextScore=score+points;setScore(nextScore);setResolved(true);sound(true);if(round===total){setIsRecord(saveBest("constellation",nextScore));setDone(true)}}else{sound(false);setFailed(s=>new Set([...s,name]));setLines(true)}}function next(){setRound(v=>v+1);setLines(false);setFailed(new Set());setResolved(false)}function restart(){setTargets(shuffle(signs).slice(0,total));setRound(1);setScore(0);setLines(false);setFailed(new Set());setResolved(false);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("constellation"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page wide-game"><GameHeading label="Osservatorio" round={round} total={total} score={score}/><section className="observatory"><div className="telescope-head"><div><span>CATALOGO Z–{String(target.index+1).padStart(2,"0")}</span><h2>Quale costellazione stai osservando?</h2></div><button className="secondary" disabled={lines} onClick={()=>setLines(true)}><Orbit/> Traccia linee <small>−250 pt</small></button></div><ConstellationMap chart={target.constellation} lines={lines||resolved}/><SignPicker onChoose={choose} failed={failed} answer={resolved?target.name:null}/>{resolved&&<div className="constellation-reveal"><p><b>{target.symbol} {target.name}.</b> {target.constellation.myth}</p>{round<total&&<button className="primary" onClick={next}>Nuova osservazione <ChevronRight/></button>}</div>}</section></main>}

function OrderGame({sound,onExit}){const total=3;const[starts,setStarts]=useState(()=>shuffle(signs.map((_,i)=>i)).slice(0,total)),[round,setRound]=useState(1),[score,setScore]=useState(0),[placed,setPlaced]=useState([]),[mistakes,setMistakes]=useState(0),[resolved,setResolved]=useState(false),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),sequence=Array.from({length:6},(_,i)=>signs[(starts[round-1]+i)%12]);
 function choose(name){if(resolved||placed.includes(name))return;const expected=sequence[placed.length].name;if(name===expected){sound(true);const next=[...placed,name];setPlaced(next);if(next.length===6){const points=Math.max(200,1000-mistakes*120),nextScore=score+points;setScore(nextScore);setResolved(true);if(round===total){setIsRecord(saveBest("order",nextScore));setDone(true)}}}else{sound(false);setMistakes(v=>v+1)}}function next(){setRound(v=>v+1);setPlaced([]);setMistakes(0);setResolved(false)}function restart(){setStarts(shuffle(signs.map((_,i)=>i)).slice(0,total));setRound(1);setScore(0);setPlaced([]);setMistakes(0);setResolved(false);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("order"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page wide-game"><GameHeading label="Ruota spezzata" round={round} total={total} score={score}/><section className="order-game"><h2>Ricostruisci 6 segni consecutivi</h2><p>La sequenza parte da <b>{sequence[0].symbol} {sequence[0].name}</b>. Seleziona i segni nel corretto ordine zodiacale.</p><div className="order-slots">{sequence.map((_,i)=><span className={placed[i]?"filled":""} key={i}>{placed[i]?<>{signs.find(s=>s.name===placed[i]).symbol}<small>{placed[i]}</small></>:i===0?"1":"?"}</span>)}</div><SignPicker onChoose={choose} failed={new Set(placed)} answer={resolved?sequence.at(-1).name:null}/>{mistakes>0&&<p className="mistakes">Tentativi errati: {mistakes} · ogni errore costa 120 punti</p>}{resolved&&round<total&&<button className="primary next-round" onClick={next}>Nuova sequenza <ChevronRight/></button>}</section></main>}

function DossierGame({sound,onExit}){const total=6;const[targets,setTargets]=useState(()=>shuffle(signs).slice(0,total)),[round,setRound]=useState(1),[score,setScore]=useState(0),[answers,setAnswers]=useState({element:"",quality:"",planet:"",opposite:""}),[result,setResult]=useState(null),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),target=targets[round-1],fields=[ ["element","Elemento",["Fuoco","Terra","Aria","Acqua"]],["quality","Modalità",["Cardinale","Fisso","Mutevole"]],["planet","Governatore",[...new Set(signs.map(s=>s.planet))]],["opposite","Segno opposto",signs.map(s=>s.name)] ];
 function verify(){const correct=fields.filter(([key])=>answers[key]===target[key]).length,points=correct*175,nextScore=score+points;setResult({correct,points});setScore(nextScore);sound(correct===4);if(round===total){setIsRecord(saveBest("dossier",nextScore));setDone(true)}}function next(){setRound(v=>v+1);setAnswers({element:"",quality:"",planet:"",opposite:""});setResult(null)}function restart(){setTargets(shuffle(signs).slice(0,total));setRound(1);setScore(0);setAnswers({element:"",quality:"",planet:"",opposite:""});setResult(null);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("dossier"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page game-page"><GameHeading label="Dossier astrale" round={round} total={total} score={score}/><section className="dossier"><div className="dossier-target"><strong>{target.symbol}</strong><div><span>COMPLETA IL PROFILO</span><h2>{target.name}</h2><p>{target.dates} · casa {target.house}</p></div></div><div className="dossier-fields">{fields.map(([key,label,options])=><label className={result?(answers[key]===target[key]?"field-correct":"field-wrong"):""} key={key}><span>{label}</span><select disabled={!!result} value={answers[key]} onChange={e=>setAnswers(a=>({...a,[key]:e.target.value}))}><option value="">Scegli…</option>{options.map(o=><option key={o}>{o}</option>)}</select>{result&&<small>{answers[key]===target[key]?"Corretto":`Soluzione: ${target[key]}`}</small>}</label>)}</div>{!result?<button className="primary wide" disabled={Object.values(answers).some(v=>!v)} onClick={verify}><FileSearch/> Verifica dossier</button>:<div className="dossier-result"><p><b>{result.correct}/4 corretti</b> · +{result.points} punti</p>{round<total&&<button className="primary" onClick={next}>Prossimo dossier <ChevronRight/></button>}</div>}</section></main>}

function ExpertGame({sound,onExit}){const total=6;const[rounds,setRounds]=useState(()=>shuffle(signs).slice(0,total).map(sign=>({sign,items:expertStatements(sign)}))),[round,setRound]=useState(1),[score,setScore]=useState(0),[selected,setSelected]=useState(new Set()),[result,setResult]=useState(null),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),current=rounds[round-1];
 function verify(){const correct=current.items.filter(i=>selected.has(i.id)===i.truth).length,points=correct*120,nextScore=score+points;setResult({correct,points});setScore(nextScore);sound(correct===6);if(round===total){setIsRecord(saveBest("expert",nextScore));setDone(true)}}function next(){setRound(v=>v+1);setSelected(new Set());setResult(null)}function restart(){setRounds(shuffle(signs).slice(0,total).map(sign=>({sign,items:expertStatements(sign)})));setRound(1);setScore(0);setSelected(new Set());setResult(null);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("expert"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page game-page"><GameHeading label="Archivio vero/falso" round={round} total={total} score={score}/><section className="expert-game"><div className="expert-title"><strong>{current.sign.symbol}</strong><div><span>SELEZIONE MULTIPLA</span><h2>{current.sign.name}</h2></div></div><p className="instruction">Seleziona <b>tutte e soltanto</b> le affermazioni vere. Il numero di risposte corrette non è indicato.</p><div className="statement-list">{current.items.map(item=>{const picked=selected.has(item.id),state=result?(item.truth?"truth":picked?"false-picked":"false"):picked?"picked":"";return <button disabled={!!result} className={state} key={item.id} onClick={()=>setSelected(old=>{const n=new Set(old);n.has(item.id)?n.delete(item.id):n.add(item.id);return n})}><span className="checkbox">{picked?<Check/>:null}</span>{item.text}{result&&<small>{item.truth?"VERA":"FALSA"}</small>}</button>})}</div>{!result?<button className="primary wide" onClick={verify}>Conferma selezione</button>:<div className="dossier-result"><p><b>{result.correct}/6 valutazioni corrette</b> · +{result.points} punti</p>{round<total&&<button className="primary" onClick={next}>Prossimo archivio <ChevronRight/></button>}</div>}</section></main>}

function SignPicker({onChoose,failed=new Set(),answer=null}){return <div className="sign-picker">{signs.map(s=><button disabled={failed.has(s.name)||!!answer} className={`${failed.has(s.name)?"failed":""} ${answer===s.name?"answer":""}`} onClick={()=>onChoose(s.name)} key={s.name}><strong>{s.symbol}</strong><span>{s.name}</span></button>)}</div>}
function ConstellationMap({chart,lines=false}){return <div className="sky-map"><div className="scan-line"/><svg viewBox="0 0 100 100" role="img" aria-label="Schema di una costellazione senza nome"><g className={lines?"links visible":"links"}>{chart.edges.map(([a,b],i)=><line key={i} x1={chart.stars[a][0]} y1={chart.stars[a][1]} x2={chart.stars[b][0]} y2={chart.stars[b][1]}/>)}</g><g>{chart.stars.map(([x,y,r],i)=><circle className={`star s${i%3}`} key={i} cx={x} cy={y} r={r/2}/>)}</g></svg><span className="coordinates">AR 00h — DEC ±00°</span></div>}

function GameHeading({label,round,total,time,score,streak,children}){return <><div className="game-heading"><div><span className="eyebrow">{label}</span><h1>{time!=null?`${time} secondi`:`Domanda ${round} di ${total}`}</h1></div><div className="score-pills"><span>🔥 {streak||0}</span><b>{score} pt</b></div></div>{children}<div className="progress"><i style={{width:`${time!=null?time/60*100:(round-1)/total*100}%`}}/></div></>}

function QuestionCard({question,choice,onChoose,revealed,onNext,disabled=false,playerAnswers=null}){return <section className="question-card"><div className="question-symbol">{question.symbol}</div><span className="question-kind">{modeInfo[question.mode]?.title}</span><h2>{question.prompt}</h2>{question.constellation&&<ConstellationMap chart={question.constellation} lines/>}<div className={`answer-grid ${question.options.length>6?"many":""}`}>{question.options.map(option=>{let state="";if(revealed)state=option===question.answer?"correct":option===choice?"wrong":"muted";return <button key={option} disabled={disabled||!!choice} onClick={()=>onChoose(option)} className={state}><span>{option}</span>{state==="correct"?<Check/>:state==="wrong"?<X/>:null}{playerAnswers&&<small>{playerAnswers.filter(a=>a.choice===option).map(a=>a.name).join(" · ")}</small>}</button>})}</div>{revealed&&question.explanation&&<div className="explanation"><p><b>{choice===question.answer?"Esatto!":"Risposta corretta: "+question.answer}</b> {question.explanation}</p>{onNext&&<button className="primary small" onClick={onNext}>Prossima <ChevronRight/></button>}</div>}</section>}

function OnlineSetup({onReady}){const[tab,setTab]=useState("create"),[name,setName]=useState(""),[roomCode,setRoomCode]=useState(""),[mode,setMode]=useState("mixed"),[rounds,setRounds]=useState(10),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e){e.preventDefault();setBusy(true);setError("");try{const s=tab==="create"?await api("/api/rooms",{name,mode,rounds}):await api(`/api/rooms/${roomCode.trim().toUpperCase()}/join`,{name});onReady(s)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main className="page setup-page"><section className="setup-card"><div className="setup-title"><span className="card-icon"><UsersRound/></span><div><span className="eyebrow">DUE GIOCATORI</span><h1>Partita online</h1></div></div><div className="tabs"><button className={tab==="create"?"active":""} onClick={()=>setTab("create")}>Crea stanza</button><button className={tab==="join"?"active":""} onClick={()=>setTab("join")}>Entra con codice</button></div><form onSubmit={submit}><label>Il tuo nome<input value={name} maxLength={18} onChange={e=>setName(e.target.value)} placeholder="Es. Mattia" autoComplete="nickname" required minLength={2}/></label>{tab==="create"?<><label>Tipo di sfida<select value={mode} onChange={e=>setMode(e.target.value)}>{onlineModes.map(m=><option value={m} key={m}>{modeInfo[m].title}</option>)}</select></label><fieldset><legend>Numero di domande</legend><div className="segmented">{[5,10,15].map(n=><button type="button" className={rounds===n?"active":""} onClick={()=>setRounds(n)} key={n}>{n}</button>)}</div></fieldset></>:<label>Codice stanza<input className="code-input" value={roomCode} maxLength={5} onChange={e=>setRoomCode(e.target.value.toUpperCase())} placeholder="ABCDE" required/></label>}{error&&<div className="error"><X/> {error}</div>}<button className="primary wide" disabled={busy}>{busy?<><LoaderCircle className="spin"/> Collegamento…</>:tab==="create"?<><Play/> Crea la stanza</>:<><Link2/> Entra nella stanza</>}</button></form><p className="privacy-note">Le stanze sono private e si aprono solo conoscendo il codice.</p></section></main>}

function OnlineRoom({session,state,sound,onLeave}){const[localChoice,setLocalChoice]=useState(null),[error,setError]=useState(""),[copied,setCopied]=useState(false),[left,setLeft]=useState(20),lastQuestion=useRef(null);const me=state?.players?.find(p=>p.id===session?.playerId),isHost=state?.hostId===session?.playerId;
 useEffect(()=>{if(!state?.question)return;if(lastQuestion.current!==state.question.id){lastQuestion.current=state.question.id;setLocalChoice(null)}},[state?.question]);
 useEffect(()=>{if(state?.status!=="playing"||!state.roundEndsAt)return;const tick=()=>setLeft(Math.max(0,Math.ceil((state.roundEndsAt-Date.now())/1000)));tick();const t=setInterval(tick,250);return()=>clearInterval(t)},[state?.status,state?.roundEndsAt,state?.question?.id]);
 useEffect(()=>{const mine=state?.status==="reveal"?state.answers?.[session?.playerId]:null;if(mine)sound(mine.correct)},[state?.status,state?.question?.id]);
 async function act(action,data={}){setError("");try{return await api(`/api/rooms/${session.code}/${action}`,{playerId:session.playerId,token:session.token,...data})}catch(e){setError(e.message)}}
 async function choose(choice){if(localChoice)return;setLocalChoice(choice);await act("answer",{choice})}
 async function copy(){await navigator.clipboard.writeText(session.code);setCopied(true);setTimeout(()=>setCopied(false),1500)}
 if(!state)return <main className="page centered"><LoaderCircle className="spin big"/><p>Collegamento alla stanza…</p></main>;
 if(state.status==="lobby")return <main className="page lobby-page"><section className="lobby-card"><span className="eyebrow"><Globe2/> STANZA PRIVATA</span><h1>Invita il secondo giocatore</h1><p>Condividi questo codice. La partita inizierà appena sarete entrambi pronti.</p><button className="room-code" onClick={copy}><span>{session.code}</span><small>{copied?<><Check/> Copiato</>:<><Copy/> Copia codice</>}</small></button><div className="players">{state.players.map((p,i)=><Player key={p.id} player={p} host={p.id===state.hostId} index={i}/>)}{state.players.length<2&&<div className="player waiting"><LoaderCircle className="spin"/><div><b>In attesa…</b><small>Il posto è libero</small></div></div>}</div><div className="lobby-settings"><span>{modeInfo[state.settings.mode].title}</span><i/> <span>{state.settings.rounds} domande</span><i/> <span>20 secondi</span></div>{error&&<div className="error"><X/> {error}</div>}{isHost?<button className="primary wide" disabled={state.players.length<2} onClick={()=>act("start")}><Play/> {state.players.length<2?"Attendi il secondo giocatore":"Inizia la sfida"}</button>:<div className="waiting-host"><LoaderCircle className="spin"/> Chi ha creato la stanza avvierà la partita</div>}<button className="text-button" onClick={onLeave}>Esci dalla stanza</button></section></main>;
 if(state.status==="finished"){const sorted=[...state.players].sort((a,b)=>b.score-a.score),winner=sorted[0].score===sorted[1].score?null:sorted[0];return <main className="page centered"><section className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">PARTITA TERMINATA</span><h1>{winner?`${winner.name} vince!`:"Pareggio perfetto!"}</h1><div className="final-scores">{sorted.map((p,i)=><div className={p.id===session.playerId?"me":""} key={p.id}><span>{i===0?"🥇":"🥈"}</span><b>{p.name}</b><strong>{p.score} pt</strong></div>)}</div>{error&&<div className="error"><X/> {error}</div>}<div className="result-actions">{isHost?<button className="primary" onClick={()=>act("rematch")}><RotateCcw/> Rivincita</button>:<div className="waiting-host"><LoaderCircle className="spin"/> In attesa della rivincita</div>}<button className="secondary" onClick={onLeave}><HomeIcon/> Menu</button></div></section></main>}
 const revealed=state.status==="reveal",answerEntries=revealed?Object.entries(state.answers).map(([id,a])=>({...a,name:state.players.find(p=>p.id===id)?.name||"Giocatore"})):[];
 return <main className="page game-page"><GameHeading label={`${modeInfo[state.settings.mode].title} · Online`} round={state.round} total={state.settings.rounds} score={me?.score||0} streak={0}><div className="versus-bar">{state.players.map(p=><div key={p.id} className={p.id===session.playerId?"me":""}><span className={p.connected?"dot on":"dot"}/><b>{p.name}</b><strong>{p.score}</strong></div>)}<span className="versus">VS</span><div className="round-clock"><Clock3/> {revealed?"Risultato":`${left}s`}</div></div></GameHeading>{error&&<div className="error"><X/> {error}</div>}<QuestionCard question={state.question} choice={localChoice} onChoose={choose} revealed={revealed} disabled={state.answeredPlayerIds?.includes(session.playerId)} playerAnswers={answerEntries}/>{!revealed&&localChoice&&<div className="answer-wait"><Check/> Risposta inviata. Aspettiamo l’altro giocatore…</div>}</main>}

function Player({player,host,index}){return <div className="player"><div className={`avatar a${index}`}>{player.name.slice(0,1).toUpperCase()}</div><div><b>{player.name} {host&&<span>HOST</span>}</b><small>{player.connected?"Connesso":"Connessione persa"}</small></div><i className={player.connected?"online-dot":""}/></div>}
function Result({score,best,isRecord,onAgain,onHome}){return <main className="page centered"><section className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">PARTITA COMPLETATA</span><h1>{score} punti</h1>{isRecord&&<div className="new-record"><Sparkles/> Nuovo record!</div>}<p>Record personale: <b>{best} punti</b></p><div className="result-actions"><button className="primary" onClick={onAgain}><RotateCcw/> Rigioca</button><button className="secondary" onClick={onHome}><Grid2X2/> Modalità</button></div></section></main>}
function Rules({onClose}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="rules-title"><button className="modal-close" onClick={onClose}><X/></button><span className="eyebrow">COME SI GIOCA</span><h2 id="rules-title">Regole rapide</h2><div className="rule-list"><div><b>Modalità diverse</b><p>Ogni prova ha regole proprie: eliminazione dei sospetti, indizi progressivi, sequenze, dossier o selezioni multiple.</p></div><div><b>Indizi e aiuti</b><p>Più informazioni richiedi, meno punti ottieni. Nell’Osservatorio tracciare le linee costa 250 punti.</p></div><div><b>Blitz estremo</b><p>Hai 60 secondi e fino a dodici alternative. Le domande non si ripetono durante la sessione.</p></div><div><b>Online</b><p>Condividi il codice con una persona. Avete la stessa prova, 20 secondi e un bonus fino a 50 punti per la velocità.</p></div></div><button className="primary wide" onClick={onClose}>Ho capito</button></section></div>}
