import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowLeft,BookOpen,Check,ChevronRight,Clock3,Copy,Crosshair,Eye,FileSearch,Gamepad2,Globe2,Grid2X2,Home as HomeIcon,Link2,LoaderCircle,Medal,Orbit,Play,RotateCcw,Sparkles,Target,Timer,Trophy,UserRound,UsersRound,Volume2,VolumeX,X,Zap} from "lucide-react";
import {buildQuestionSet,detectiveQuestions,expertStatements,modeInfo,onlineModes,progressiveClues,scoreCipher,shuffle,signs,soloModes} from "./gameData.js";

const modeIcons={guesswho:Eye,clues:FileSearch,constellation:Orbit,cipher:Grid2X2,dossier:Crosshair,expert:BookOpen,logic:Target,mixed:Gamepad2,blitz:Timer};
const modeColors={guesswho:"#a78bfa",clues:"#60a5fa",constellation:"#22d3ee",cipher:"#34d399",dossier:"#f472b6",expert:"#fb7185",logic:"#818cf8",mixed:"#ffc857",blitz:"#f59e0b"};
const api=async(path,data)=>{const r=await fetch(path,{method:data?"POST":"GET",headers:data?{"content-type":"application/json"}:{},body:data?JSON.stringify(data):undefined});const value=await r.json().catch(()=>({}));if(!r.ok)throw new Error(value.error||"Connessione non riuscita.");return value};

export default function App(){
 const[screen,setScreen]=useState("home"),[soloMode,setSoloMode]=useState("mixed"),[sound,setSound]=useState(()=>localStorage.getItem("zodiac-sound")!=="off"),[rules,setRules]=useState(false),[session,setSession]=useState(null),[onlineState,setOnlineState]=useState(null),[connection,setConnection]=useState("online");
 useEffect(()=>localStorage.setItem("zodiac-sound",sound?"on":"off"),[sound]);
 useEffect(()=>{if(!session)return;sessionStorage.setItem("zodiac-session",JSON.stringify(session));let source;
  const connect=()=>{source=new EventSource(`/api/events?code=${encodeURIComponent(session.code)}&playerId=${encodeURIComponent(session.playerId)}&token=${encodeURIComponent(session.token)}`);source.onopen=()=>setConnection("online");source.onmessage=e=>{setOnlineState(JSON.parse(e.data));setConnection("online")};source.onerror=()=>setConnection("reconnecting")};connect();return()=>source?.close()},[session]);
 function tone(ok=true){if(!sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?660:190;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.16);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.16)}catch{}}
 function goHome(){setScreen("home");setSession(null);setOnlineState(null);sessionStorage.removeItem("zodiac-session")}
 return <div className="app-shell"><Stars/><Topbar screen={screen} onBack={()=>screen==="solo"?setScreen("soloModes"):screen==="online"?goHome():setScreen("home")} sound={sound} setSound={setSound} openRules={()=>setRules(true)} connection={screen==="online"?connection:null}/>
  {screen==="home"&&<Home onSolo={()=>setScreen("soloModes")} onOnline={()=>setScreen("onlineSetup")} onReconnect={()=>{try{const s=JSON.parse(sessionStorage.getItem("zodiac-session"));if(s){setSession(s);setScreen("online")}}catch{}}}/>} 
  {screen==="soloModes"&&<ModeMenu onChoose={m=>{setSoloMode(m);setScreen("solo")}}/>}
  {screen==="solo"&&<SoloGame mode={soloMode} sound={tone} onExit={()=>setScreen("soloModes")}/>}
  {screen==="onlineSetup"&&<OnlineSetup onReady={s=>{setSession(s);setOnlineState(s.state);setScreen("online")}}/>}
  {screen==="online"&&<OnlineRoom session={session} state={onlineState} sound={tone} onLeave={goHome}/>} {rules&&<Rules onClose={()=>setRules(false)}/>}</div>
}

function Stars(){return <div className="stars" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div>}
function Topbar({screen,onBack,sound,setSound,openRules,connection}){return <header className="topbar"><div>{screen!=="home"&&<button className="icon-text" onClick={onBack}><ArrowLeft size={18}/> Indietro</button>}</div><div className="brand-mini"><span>✦</span> ZODIACO ARENA</div><div className="top-actions">{connection&&<span className={`connection ${connection}`}>{connection==="online"?"Online":"Riconnessione…"}</span>}<button className="icon-button" onClick={()=>setSound(!sound)} aria-label={sound?"Disattiva suoni":"Attiva suoni"}>{sound?<Volume2/>:<VolumeX/>}</button><button className="icon-button" onClick={openRules} aria-label="Regole"><BookOpen/></button></div></header>}

function Home({onSolo,onOnline,onReconnect}){const hasSession=!!sessionStorage.getItem("zodiac-session");return <main className="page home-page"><section className="hero"><div className="eyebrow"><Sparkles size={15}/> IL QUIZ DELLE STELLE</div><h1>Quanto conosci<br/><em>lo Zodiaco?</em></h1><p>Scegli la tua sfida: allenati da solo oppure affronta un’altra persona in tempo reale.</p></section><section className="play-choices"><button className="play-card solo" onClick={onSolo}><div className="card-icon"><UserRound/></div><div><small>ALLENAMENTO</small><h2>Giocatore singolo</h2><p>Nove modalità, record personali e serie di risposte esatte.</p></div><ChevronRight/></button><button className="play-card online" onClick={onOnline}><div className="live-pill">● LIVE</div><div className="card-icon"><UsersRound/></div><div><small>SFIDA ONLINE</small><h2>Due giocatori</h2><p>Crea una stanza privata e manda il codice al tuo avversario.</p></div><ChevronRight/></button></section>{hasSession&&<button className="resume" onClick={onReconnect}><Link2 size={17}/> Rientra nell’ultima stanza</button>}<div className="feature-row"><span><Zap/> Punti velocità</span><span><Trophy/> Record salvati</span><span><Globe2/> Online in tempo reale</span></div></main>}

function ModeMenu({onChoose}){return <main className="page"><section className="section-heading"><div><span className="eyebrow"><UserRound size={15}/> LIVELLO ESPERTO</span><h1>Scegli la modalità</h1><p>Prove procedurali di deduzione, osservazione e strategia. Il gioco ricorda anche le domande viste nelle sessioni recenti.</p></div></section><div className="mode-grid">{soloModes.map((m,i)=>{const Icon=modeIcons[m],best=readBest(m);return <button className="mode-card" onClick={()=>onChoose(m)} key={m} style={{"--mode":modeColors[m]}}><div className="mode-top"><span className="mode-icon"><Icon/></span><span className="mode-number">0{i+1}</span></div><h2>{modeInfo[m].title}</h2><p>{modeInfo[m].description}</p><footer>{best?<span><Medal size={15}/> Record {best}</span>:<span>Mai giocata</span>}<ChevronRight/></footer></button>})}</div></main>}

function readBest(mode){try{return JSON.parse(localStorage.getItem("zodiac-bests")||"{}")[mode]||0}catch{return 0}}
function saveBest(mode,score){let all={};try{all=JSON.parse(localStorage.getItem("zodiac-bests")||"{}")}catch{}if(score>(all[mode]||0)){all[mode]=score;localStorage.setItem("zodiac-bests",JSON.stringify(all));return true}return false}

function SoloGame(props){if(props.mode==="guesswho")return <GuessWhoGame {...props}/>;if(props.mode==="clues")return <ClueGame {...props}/>;if(props.mode==="constellation")return <ConstellationGame {...props}/>;if(props.mode==="cipher")return <CipherGame {...props}/>;if(props.mode==="dossier")return <DossierGame {...props}/>;if(props.mode==="expert")return <ExpertGame {...props}/>;return <ClassicGame {...props}/>}

const questionKey=q=>`${q.mode}:${q.prompt}:${q.answer}:${q.view?.rotation??""}:${q.view?.mirror??""}`;
function freshDeck(mode,count){const storageKey=`zodiac-recent-${mode}`;let recent=[];try{recent=JSON.parse(localStorage.getItem(storageKey)||"[]")}catch{}const pool=buildQuestionSet(mode,Math.max(count*3,count+20)),blocked=new Set(recent),deck=[...pool.filter(q=>!blocked.has(questionKey(q))),...pool.filter(q=>blocked.has(questionKey(q)))].slice(0,count);localStorage.setItem(storageKey,JSON.stringify([...recent,...deck.map(questionKey)].slice(-160)));return deck}

function ClassicGame({mode,sound,onExit}){const isBlitz=mode==="blitz",deckMode=isBlitz?"mixed":mode,total=isBlitz?40:10;const[deck,setDeck]=useState(()=>freshDeck(deckMode,total)),[round,setRound]=useState(1),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[choice,setChoice]=useState(null),[time,setTime]=useState(60),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),q=deck[Math.min(round-1,deck.length-1)];
 useEffect(()=>{if(!isBlitz||done)return;const t=setInterval(()=>setTime(v=>{if(v<=1){setDone(true);return 0}return v-1}),1000);return()=>clearInterval(t)},[isBlitz,done]);
 useEffect(()=>{if(done)setIsRecord(saveBest(mode,score))},[done,mode,score]);
 function choose(value){if(choice||done)return;setChoice(value);const ok=value===q.answer;sound(ok);if(ok){setScore(s=>s+140+Math.min(streak,5)*25);setStreak(s=>s+1)}else setStreak(0);if(isBlitz)setTimeout(next,380)}
 function next(){if(round>=total){setDone(true);return}setRound(r=>r+1);setChoice(null)}
 function restart(){setDeck(freshDeck(deckMode,total));setRound(1);setScore(0);setStreak(0);setChoice(null);setTime(60);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest(mode),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page game-page"><GameHeading label={modeInfo[mode].title} round={isBlitz?null:round} total={total} time={isBlitz?time:null} score={score} streak={streak}/><QuestionCard question={q} choice={choice} onChoose={choose} revealed={!!choice} onNext={isBlitz?null:next}/></main>}

function GuessWhoGame({sound,onExit}){const total=5;const[targets,setTargets]=useState(()=>shuffle(signs).slice(0,total)),[round,setRound]=useState(1),[score,setScore]=useState(0),[asked,setAsked]=useState([]),[wrongNames,setWrongNames]=useState(new Set()),[selected,setSelected]=useState(null),[resolved,setResolved]=useState(null),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),target=targets[round-1],questions=useMemo(()=>shuffle(detectiveQuestions()).slice(0,18),[round]),remaining=signs.filter(s=>!wrongNames.has(s.name)&&asked.every(a=>a.test(s)===a.answer));
 function ask(question){if(resolved||asked.some(a=>a.id===question.id))return;const answer=question.test(target);setAsked(old=>[...old,{...question,answer}]);setSelected(null)}
 function accuse(){if(!selected||resolved)return;if(selected===target.name){const points=Math.max(100,1000-asked.length*85-wrongNames.size*160),nextScore=score+points;sound(true);setScore(nextScore);setResolved(points);if(round===total){setIsRecord(saveBest("guesswho",nextScore));setDone(true)}}else{sound(false);setWrongNames(old=>new Set([...old,selected]));setSelected(null)}}
 function next(){setRound(v=>v+1);setAsked([]);setWrongNames(new Set());setSelected(null);setResolved(null)}
 function restart(){setTargets(shuffle(signs).slice(0,total));setRound(1);setScore(0);setAsked([]);setWrongNames(new Set());setSelected(null);setResolved(null);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("guesswho"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page wide-game"><GameHeading label="Indovina Chi: interrogatorio" round={round} total={total} score={score}/><section className="detective-panel"><div className="interrogation-head"><div><span>DOMANDE FATTE · {asked.length}</span><h2>Scegli cosa chiedere all’identità segreta</h2></div><strong>{remaining.length} sospetti compatibili</strong></div><div className="question-bank">{questions.map(q=>{const result=asked.find(a=>a.id===q.id);return <button className={result?(result.answer?"yes":"no"):""} disabled={!!result||!!resolved} key={q.id} onClick={()=>ask(q)}><span>{q.text}</span>{result&&<b>{result.answer?"SÌ":"NO"}</b>}</button>})}</div><div className="guess-board">{signs.map(s=>{const excluded=!remaining.some(r=>r.name===s.name);return <article className={`${excluded?"excluded":""} ${selected===s.name?"selected":""} ${resolved&&s.name===target.name?"correct":""}`} key={s.name}><button className="suspect" disabled={excluded||!!resolved} onClick={()=>setSelected(s.name)}><strong>{s.symbol}</strong><span>{s.name}</span></button></article>})}</div><div className="accuse-bar">{resolved?<><p><Check/> Identità scoperta: <b>{target.name}</b> · +{resolved} punti</p>{round<total&&<button className="primary" onClick={next}>Prossimo caso <ChevronRight/></button>}</>:<><p>{selected?<>Accusa <b>{selected}</b>? Un errore lo elimina e costa 160 punti.</>:"Le risposte sì/no eliminano automaticamente i profili incompatibili."}</p><button className="primary" disabled={!selected} onClick={accuse}><Crosshair/> Accusa</button></>}</div></section></main>}

function ClueGame({sound,onExit}){const total=6,values=[650,500,360,240,150,80];const[targets,setTargets]=useState(()=>shuffle(signs).slice(0,total)),[round,setRound]=useState(1),[score,setScore]=useState(0),[level,setLevel]=useState(0),[failed,setFailed]=useState(new Set()),[resolved,setResolved]=useState(false),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),target=targets[round-1],clues=useMemo(()=>progressiveClues(target),[target.name]);
 function choose(name){if(resolved||failed.has(name))return;if(name===target.name){const nextScore=score+values[level];setScore(nextScore);setResolved(true);sound(true);if(round===total){setIsRecord(saveBest("clues",nextScore));setDone(true)}}else{sound(false);setFailed(s=>new Set([...s,name]));setLevel(v=>Math.min(5,v+1))}}
 function next(){setRound(v=>v+1);setLevel(0);setFailed(new Set());setResolved(false)}function restart(){setTargets(shuffle(signs).slice(0,total));setRound(1);setScore(0);setLevel(0);setFailed(new Set());setResolved(false);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("clues"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page wide-game"><GameHeading label="Rivelazione" round={round} total={total} score={score}/><section className="revelation"><div className="value-orbit"><span>VALORE INDIZIO</span><strong>{values[level]}</strong><small>punti</small></div><div className="active-clue"><small>INDIZIO {level+1} DI 6</small><h2>{clues[level]}</h2><div className="clue-dots">{clues.map((_,i)=><i className={i<=level?"on":""} key={i}/>)}</div></div><SignPicker onChoose={choose} failed={failed} answer={resolved?target.name:null}/>{resolved&&round<total&&<button className="primary next-round" onClick={next}>Continua <ChevronRight/></button>}</section></main>}

function ConstellationGame({sound,onExit}){const total=8;const[targets,setTargets]=useState(()=>shuffle(signs).slice(0,total)),[round,setRound]=useState(1),[score,setScore]=useState(0),[lines,setLines]=useState(false),[failed,setFailed]=useState(new Set()),[resolved,setResolved]=useState(false),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),target=targets[round-1],view=useMemo(()=>({rotation:Math.floor(Math.random()*8)*45,mirror:Math.random()>.5,density:[.55,.72,1][Math.floor(Math.random()*3)]}),[target.name]);
 function choose(name){if(resolved||failed.has(name))return;if(name===target.name){const points=Math.max(100,(lines?350:600)-failed.size*100),nextScore=score+points;setScore(nextScore);setResolved(true);sound(true);if(round===total){setIsRecord(saveBest("constellation",nextScore));setDone(true)}}else{sound(false);setFailed(s=>new Set([...s,name]));setLines(true)}}function next(){setRound(v=>v+1);setLines(false);setFailed(new Set());setResolved(false)}function restart(){setTargets(shuffle(signs).slice(0,total));setRound(1);setScore(0);setLines(false);setFailed(new Set());setResolved(false);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("constellation"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page wide-game"><GameHeading label="Osservatorio J2000" round={round} total={total} score={score}/><section className="observatory"><div className="telescope-head"><div><span>CAMPO XHIP · OTTICA {view.mirror?"SPECCHIATA":"DIRETTA"} · {view.rotation}°</span><h2>Riconosci coordinate, distanze e luminosità reali</h2></div><button className="secondary" disabled={lines} onClick={()=>setLines(true)}><Orbit/> Sovrapponi figura <small>−250 pt</small></button></div><ConstellationMap chart={target.constellation} lines={lines||resolved} view={view}/><SignPicker onChoose={choose} failed={failed} answer={resolved?target.name:null}/>{resolved&&<div className="constellation-reveal"><p><b>{target.symbol} {target.name}.</b> {target.constellation.myth}</p>{round<total&&<button className="primary" onClick={next}>Nuova osservazione <ChevronRight/></button>}</div>}</section></main>}

function CipherGame({sound,onExit}){const total=4,limit=8,makeSecrets=()=>Array.from({length:total},()=>shuffle(signs).slice(0,4).map(s=>s.name));const[secrets,setSecrets]=useState(makeSecrets),[round,setRound]=useState(1),[score,setScore]=useState(0),[guess,setGuess]=useState([]),[history,setHistory]=useState([]),[resolved,setResolved]=useState(null),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),secret=secrets[round-1];
 function choose(name){if(resolved||guess.length===4||guess.includes(name))return;setGuess(old=>[...old,name])}
 function submit(){if(guess.length!==4||resolved)return;const result=scoreCipher(secret,guess),entry={guess,result},nextHistory=[...history,entry];setHistory(nextHistory);setGuess([]);sound(result.exact===4);if(result.exact===4){const points=Math.max(220,1200-history.length*140),nextScore=score+points;setScore(nextScore);setResolved({won:true,points});if(round===total){setIsRecord(saveBest("cipher",nextScore));setDone(true)}}else if(nextHistory.length>=limit){setResolved({won:false,points:0});if(round===total){setIsRecord(saveBest("cipher",score));setDone(true)}}}
 function next(){setRound(v=>v+1);setGuess([]);setHistory([]);setResolved(null)}function restart(){setSecrets(makeSecrets());setRound(1);setScore(0);setGuess([]);setHistory([]);setResolved(null);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("cipher"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page wide-game"><GameHeading label="Codice Astrale" round={round} total={total} score={score}/><section className="cipher-game"><div className="cipher-head"><div><span>11.880 COMBINAZIONI · NESSUNA RIPETIZIONE</span><h2>Decifra quattro segni e la loro posizione</h2></div><strong>{limit-history.length} tentativi</strong></div><div className="cipher-legend"><span><i className="exact"/> stella allineata = segno e posizione esatti</span><span><i className="misplaced"/> stella orbitante = segno giusto, posizione errata</span></div><div className="cipher-history">{history.map((entry,i)=><div className="cipher-row" key={i}><b>{String(i+1).padStart(2,"0")}</b><div>{entry.guess.map(name=><span key={name}>{signs.find(s=>s.name===name).symbol}</span>)}</div><small><em>{entry.result.exact} ✦</em><em>{entry.result.misplaced} ◌</em></small></div>)}</div>{!resolved&&<><div className="cipher-current">{Array.from({length:4},(_,i)=><span className={guess[i]?"filled":""} key={i}>{guess[i]?<><b>{signs.find(s=>s.name===guess[i]).symbol}</b><small>{guess[i]}</small></>:"?"}</span>)}</div><SignPicker onChoose={choose} failed={new Set(guess)}/><div className="cipher-actions"><button className="secondary" disabled={!guess.length} onClick={()=>setGuess(old=>old.slice(0,-1))}>Annulla ultimo</button><button className="primary" disabled={guess.length!==4} onClick={submit}>Analizza codice <ChevronRight/></button></div></>}{resolved&&<div className="cipher-reveal"><p>{resolved.won?<><Check/> Codice decifrato: <b>{secret.join(" · ")}</b> · +{resolved.points} punti</>:<>Codice esaurito: <b>{secret.join(" · ")}</b></>}</p>{round<total&&<button className="primary" onClick={next}>Nuovo codice <ChevronRight/></button>}</div>}</section></main>}

function DossierGame({sound,onExit}){const total=6;const[targets,setTargets]=useState(()=>shuffle(signs).slice(0,total)),[round,setRound]=useState(1),[score,setScore]=useState(0),[answers,setAnswers]=useState({}),[result,setResult]=useState(null),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),target=targets[round-1],previous=signs[(target.index+11)%12],following=signs[(target.index+1)%12],opposing=signs.find(s=>s.name===target.opposite),elements=["Fuoco","Terra","Aria","Acqua"],qualities=["Cardinale","Fisso","Mutevole"],planets=[...new Set(signs.map(s=>s.planet))],fields=useMemo(()=>shuffle([["element","Elemento",elements,target.element],["quality","Modalità",qualities,target.quality],["planet","Governatore",planets,target.planet],["opposite","Segno opposto",signs.map(s=>s.name),target.opposite],["polarity","Polarità",["Positiva","Negativa"],target.polarity],["previousElement","Elemento del predecessore",elements,previous.element],["previousQuality","Modalità del predecessore",qualities,previous.quality],["nextElement","Elemento del successore",elements,following.element],["nextQuality","Modalità del successore",qualities,following.quality],["oppositeElement","Elemento dell’opposto",elements,opposing.element],["oppositePlanet","Governatore dell’opposto",planets,opposing.planet]]).slice(0,6),[target.name]);
 function verify(){const correct=fields.filter(([key,,,expected])=>answers[key]===expected).length,points=correct*145,nextScore=score+points;setResult({correct,points});setScore(nextScore);sound(correct===6);if(round===total){setIsRecord(saveBest("dossier",nextScore));setDone(true)}}function next(){setRound(v=>v+1);setAnswers({});setResult(null)}function restart(){setTargets(shuffle(signs).slice(0,total));setRound(1);setScore(0);setAnswers({});setResult(null);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("dossier"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page game-page"><GameHeading label="Dossier astrale" round={round} total={total} score={score}/><section className="dossier"><div className="dossier-target"><strong>{target.symbol}</strong><div><span>PROFILO A SEI VARIABILI</span><h2>{target.name}</h2><p>Nessun numero di casa: servono memoria e relazioni nella ruota.</p></div></div><div className="dossier-fields">{fields.map(([key,label,options,expected])=><label className={result?(answers[key]===expected?"field-correct":"field-wrong"):""} key={key}><span>{label}</span><select disabled={!!result} value={answers[key]||""} onChange={e=>setAnswers(a=>({...a,[key]:e.target.value}))}><option value="">Scegli…</option>{options.map(o=><option key={o}>{o}</option>)}</select>{result&&<small>{answers[key]===expected?"Corretto":`Soluzione: ${expected}`}</small>}</label>)}</div>{!result?<button className="primary wide" disabled={fields.some(([key])=>!answers[key])} onClick={verify}><FileSearch/> Verifica dossier</button>:<div className="dossier-result"><p><b>{result.correct}/6 corretti</b> · +{result.points} punti</p>{round<total&&<button className="primary" onClick={next}>Prossimo dossier <ChevronRight/></button>}</div>}</section></main>}

function ExpertGame({sound,onExit}){const total=6;const[rounds,setRounds]=useState(()=>shuffle(signs).slice(0,total).map(sign=>({sign,items:expertStatements(sign)}))),[round,setRound]=useState(1),[score,setScore]=useState(0),[selected,setSelected]=useState(new Set()),[result,setResult]=useState(null),[done,setDone]=useState(false),[isRecord,setIsRecord]=useState(false),current=rounds[round-1];
 function verify(){const correct=current.items.filter(i=>selected.has(i.id)===i.truth).length,points=correct*120,nextScore=score+points;setResult({correct,points});setScore(nextScore);sound(correct===6);if(round===total){setIsRecord(saveBest("expert",nextScore));setDone(true)}}function next(){setRound(v=>v+1);setSelected(new Set());setResult(null)}function restart(){setRounds(shuffle(signs).slice(0,total).map(sign=>({sign,items:expertStatements(sign)})));setRound(1);setScore(0);setSelected(new Set());setResult(null);setDone(false);setIsRecord(false)}
 if(done)return <Result score={score} best={Math.max(readBest("expert"),score)} isRecord={isRecord} onAgain={restart} onHome={onExit}/>;
 return <main className="page game-page"><GameHeading label="Archivio vero/falso" round={round} total={total} score={score}/><section className="expert-game"><div className="expert-title"><strong>{current.sign.symbol}</strong><div><span>SELEZIONE MULTIPLA</span><h2>{current.sign.name}</h2></div></div><p className="instruction">Seleziona <b>tutte e soltanto</b> le affermazioni vere. Il numero di risposte corrette non è indicato.</p><div className="statement-list">{current.items.map(item=>{const picked=selected.has(item.id),state=result?(item.truth?"truth":picked?"false-picked":"false"):picked?"picked":"";return <button disabled={!!result} className={state} key={item.id} onClick={()=>setSelected(old=>{const n=new Set(old);n.has(item.id)?n.delete(item.id):n.add(item.id);return n})}><span className="checkbox">{picked?<Check/>:null}</span>{item.text}{result&&<small>{item.truth?"VERA":"FALSA"}</small>}</button>})}</div>{!result?<button className="primary wide" onClick={verify}>Conferma selezione</button>:<div className="dossier-result"><p><b>{result.correct}/6 valutazioni corrette</b> · +{result.points} punti</p>{round<total&&<button className="primary" onClick={next}>Prossimo archivio <ChevronRight/></button>}</div>}</section></main>}

function SignPicker({onChoose,failed=new Set(),answer=null}){return <div className="sign-picker">{signs.map(s=><button disabled={failed.has(s.name)||!!answer} className={`${failed.has(s.name)?"failed":""} ${answer===s.name?"answer":""}`} onClick={()=>onChoose(s.name)} key={s.name}><strong>{s.symbol}</strong><span>{s.name}</span></button>)}</div>}
function ConstellationMap({chart,lines=false,view={rotation:0,mirror:false,density:1}}){const transform=`translate(50 50) rotate(${view.rotation||0}) scale(${view.mirror?-1:1} 1) translate(-50 -50)`,field=chart.field.slice(0,Math.ceil(chart.field.length*(view.density||1))),radius=mag=>Math.max(.3,1.55-(mag+1)*.17);return <div className="sky-map"><div className="scan-line"/><svg viewBox="0 0 100 100" role="img" aria-label="Campo stellare astronomico senza nome"><g transform={transform}><g className="field-stars">{field.map(([x,y,mag],i)=><circle key={i} cx={x} cy={y} r={Math.max(.12,radius(mag)*.48)}/>)}</g><g className={lines?"links visible":"links"}>{chart.edges.map(([a,b],i)=><line key={i} x1={chart.stars[a][0]} y1={chart.stars[a][1]} x2={chart.stars[b][0]} y2={chart.stars[b][1]}/>)}</g><g>{chart.stars.map(([x,y,mag],i)=><circle className={`star s${i%3}`} key={i} cx={x} cy={y} r={radius(mag)}/>)}</g></g></svg><span className="coordinates">J2000 · CATALOGO XHIP · MAGNITUDINE RELATIVA</span></div>}

function GameHeading({label,round,total,time,score,streak,children}){return <><div className="game-heading"><div><span className="eyebrow">{label}</span><h1>{time!=null?`${time} secondi`:`Domanda ${round} di ${total}`}</h1></div><div className="score-pills"><span>🔥 {streak||0}</span><b>{score} pt</b></div></div>{children}<div className="progress"><i style={{width:`${time!=null?time/60*100:(round-1)/total*100}%`}}/></div></>}

function QuestionCard({question,choice,onChoose,revealed,onNext,disabled=false,playerAnswers=null}){return <section className="question-card"><div className="question-symbol">{question.symbol}</div><span className="question-kind">{modeInfo[question.mode]?.title}</span><h2>{question.prompt}</h2>{question.constellation&&<ConstellationMap chart={question.constellation} lines={revealed} view={question.view}/>}<div className={`answer-grid ${question.options.length>6?"many":""}`}>{question.options.map(option=>{let state="";if(revealed)state=option===question.answer?"correct":option===choice?"wrong":"muted";return <button key={option} disabled={disabled||!!choice} onClick={()=>onChoose(option)} className={state}><span>{option}</span>{state==="correct"?<Check/>:state==="wrong"?<X/>:null}{playerAnswers&&<small>{playerAnswers.filter(a=>a.choice===option).map(a=>a.name).join(" · ")}</small>}</button>})}</div>{revealed&&question.explanation&&<div className="explanation"><p><b>{choice===question.answer?"Esatto!":"Risposta corretta: "+question.answer}</b> {question.explanation}</p>{onNext&&<button className="primary small" onClick={onNext}>Prossima <ChevronRight/></button>}</div>}</section>}

function OnlineSetup({onReady}){const[tab,setTab]=useState("create"),[name,setName]=useState(""),[roomCode,setRoomCode]=useState(""),[mode,setMode]=useState("mixed"),[rounds,setRounds]=useState(10),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e){e.preventDefault();setBusy(true);setError("");try{const s=tab==="create"?await api("/api/rooms",{name,mode,rounds}):await api(`/api/rooms/${roomCode.trim().toUpperCase()}/join`,{name});onReady(s)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main className="page setup-page"><section className="setup-card"><div className="setup-title"><span className="card-icon"><UsersRound/></span><div><span className="eyebrow">DUE GIOCATORI</span><h1>Partita online</h1></div></div><div className="tabs"><button className={tab==="create"?"active":""} onClick={()=>setTab("create")}>Crea stanza</button><button className={tab==="join"?"active":""} onClick={()=>setTab("join")}>Entra con codice</button></div><form onSubmit={submit}><label>Il tuo nome<input value={name} maxLength={18} onChange={e=>setName(e.target.value)} placeholder="Es. Mattia" autoComplete="nickname" required minLength={2}/></label>{tab==="create"?<><label>Tipo di sfida<select value={mode} onChange={e=>setMode(e.target.value)}>{onlineModes.map(m=><option value={m} key={m}>{modeInfo[m].title}</option>)}</select></label><fieldset><legend>Numero di domande</legend><div className="segmented">{[5,10,15].map(n=><button type="button" className={rounds===n?"active":""} onClick={()=>setRounds(n)} key={n}>{n}</button>)}</div></fieldset></>:<label>Codice stanza<input className="code-input" value={roomCode} maxLength={5} onChange={e=>setRoomCode(e.target.value.toUpperCase())} placeholder="ABCDE" required/></label>}{error&&<div className="error"><X/> {error}</div>}<button className="primary wide" disabled={busy}>{busy?<><LoaderCircle className="spin"/> Collegamento…</>:tab==="create"?<><Play/> Crea la stanza</>:<><Link2/> Entra nella stanza</>}</button></form><p className="privacy-note">Le stanze sono private e si aprono solo conoscendo il codice.</p></section></main>}

function OnlineRoom({session,state,sound,onLeave}){const[localChoice,setLocalChoice]=useState(null),[error,setError]=useState(""),[copied,setCopied]=useState(false),[left,setLeft]=useState(20),lastQuestion=useRef(null);const me=state?.players?.find(p=>p.id===session?.playerId),isHost=state?.hostId===session?.playerId;
 useEffect(()=>{if(!state?.question)return;if(lastQuestion.current!==state.question.id){lastQuestion.current=state.question.id;setLocalChoice(null)}},[state?.question]);
 useEffect(()=>{if(state?.status!=="playing"||!state.roundEndsAt)return;const tick=()=>setLeft(Math.max(0,Math.ceil((state.roundEndsAt-Date.now())/1000)));tick();const t=setInterval(tick,250);return()=>clearInterval(t)},[state?.status,state?.roundEndsAt,state?.question?.id]);
 useEffect(()=>{const mine=state?.status==="reveal"?state.answers?.[session?.playerId]:null;if(mine)sound(mine.correct)},[state?.status,state?.question?.id]);
 async function act(action,data={}){setError("");try{return await api(`/api/rooms/${session.code}/${action}`,{playerId:session.playerId,token:session.token,...data})}catch(e){setError(e.message)}}
 async function choose(choice){if(localChoice)return;setLocalChoice(choice);await act("answer",{choice})}
 async function copy(){await navigator.clipboard.writeText(session.code);setCopied(true);setTimeout(()=>setCopied(false),1500)}
 if(!state)return <main className="page centered"><LoaderCircle className="spin big"/><p>Collegamento alla stanza…</p></main>;
 if(state.status==="lobby")return <main className="page lobby-page"><section className="lobby-card"><span className="eyebrow"><Globe2/> STANZA PRIVATA</span><h1>Invita il secondo giocatore</h1><p>Condividi questo codice. La partita inizierà appena sarete entrambi pronti.</p><button className="room-code" onClick={copy}><span>{session.code}</span><small>{copied?<><Check/> Copiato</>:<><Copy/> Copia codice</>}</small></button><div className="players">{state.players.map((p,i)=><Player key={p.id} player={p} host={p.id===state.hostId} index={i}/>)}{state.players.length<2&&<div className="player waiting"><LoaderCircle className="spin"/><div><b>In attesa…</b><small>Il posto è libero</small></div></div>}</div><div className="lobby-settings"><span>{modeInfo[state.settings.mode].title}</span><i/> <span>{state.settings.rounds} domande</span><i/> <span>20 secondi</span></div>{error&&<div className="error"><X/> {error}</div>}{isHost?<button className="primary wide" disabled={state.players.length<2} onClick={()=>act("start")}><Play/> {state.players.length<2?"Attendi il secondo giocatore":"Inizia la sfida"}</button>:<div className="waiting-host"><LoaderCircle className="spin"/> Chi ha creato la stanza avvierà la partita</div>}<button className="text-button" onClick={onLeave}>Esci dalla stanza</button></section></main>;
 if(state.status==="finished"){const sorted=[...state.players].sort((a,b)=>b.score-a.score),winner=sorted[0].score===sorted[1].score?null:sorted[0];return <main className="page centered"><section className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">PARTITA TERMINATA</span><h1>{winner?`${winner.name} vince!`:"Pareggio perfetto!"}</h1><div className="final-scores">{sorted.map((p,i)=><div className={p.id===session.playerId?"me":""} key={p.id}><span>{i===0?"🥇":"🥈"}</span><b>{p.name}</b><strong>{p.score} pt</strong></div>)}</div>{error&&<div className="error"><X/> {error}</div>}<div className="result-actions">{isHost?<button className="primary" onClick={()=>act("rematch")}><RotateCcw/> Rivincita</button>:<div className="waiting-host"><LoaderCircle className="spin"/> In attesa della rivincita</div>}<button className="secondary" onClick={onLeave}><HomeIcon/> Menu</button></div></section></main>}
 const revealed=state.status==="reveal",answerEntries=revealed?Object.entries(state.answers).map(([id,a])=>({...a,name:state.players.find(p=>p.id===id)?.name||"Giocatore"})):[];
 return <main className="page game-page"><GameHeading label={`${modeInfo[state.settings.mode].title} · Online`} round={state.round} total={state.settings.rounds} score={me?.score||0} streak={0}><div className="versus-bar">{state.players.map(p=><div key={p.id} className={p.id===session.playerId?"me":""}><span className={p.connected?"dot on":"dot"}/><b>{p.name}</b><strong>{p.score}</strong></div>)}<span className="versus">VS</span><div className="round-clock"><Clock3/> {revealed?"Risultato":`${left}s`}</div></div></GameHeading>{error&&<div className="error"><X/> {error}</div>}<QuestionCard question={state.question} choice={localChoice} onChoose={choose} revealed={revealed} disabled={state.answeredPlayerIds?.includes(session.playerId)} playerAnswers={answerEntries}/>{!revealed&&localChoice&&<div className="answer-wait"><Check/> Risposta inviata. Aspettiamo l’altro giocatore…</div>}</main>}

function Player({player,host,index}){return <div className="player"><div className={`avatar a${index}`}>{player.name.slice(0,1).toUpperCase()}</div><div><b>{player.name} {host&&<span>HOST</span>}</b><small>{player.connected?"Connesso":"Connessione persa"}</small></div><i className={player.connected?"online-dot":""}/></div>}
function Result({score,best,isRecord,onAgain,onHome}){return <main className="page centered"><section className="result-card"><div className="trophy"><Trophy/></div><span className="eyebrow">PARTITA COMPLETATA</span><h1>{score} punti</h1>{isRecord&&<div className="new-record"><Sparkles/> Nuovo record!</div>}<p>Record personale: <b>{best} punti</b></p><div className="result-actions"><button className="primary" onClick={onAgain}><RotateCcw/> Rigioca</button><button className="secondary" onClick={onHome}><Grid2X2/> Modalità</button></div></section></main>}
function Rules({onClose}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="rules-title"><button className="modal-close" onClick={onClose}><X/></button><span className="eyebrow">COME SI GIOCA</span><h2 id="rules-title">Regole rapide</h2><div className="rule-list"><div><b>Deduzione, non suggerimenti</b><p>In Indovina Chi scegli domande sì/no; in Rivelazione ogni errore apre un indizio relazionale. Nessuna posizione di casa rivela la soluzione.</p></div><div><b>Codice Astrale</b><p>Trova quattro segni ordinati: ✦ indica posto esatto, ◌ un segno corretto nel posto sbagliato. Hai otto tentativi.</p></div><div><b>Osservatorio J2000</b><p>Coordinate e luminosità derivano da un catalogo reale. Rotazione e specchio cambiano a ogni campo; la sovrapposizione delle linee costa punti.</p></div><div><b>Online</b><p>Condividi il codice con una persona. Avete la stessa prova, 20 secondi e un bonus fino a 50 punti per la velocità.</p></div></div><button className="primary wide" onClick={onClose}>Ho capito</button></section></div>}
