export const extraPortraitScenes={
 Ariete:[
  ["Lavoro e responsabilità","In una riunione bloccata da troppi rinvii prende la parola, propone una prova di ventiquattro ore e si assume personalmente il rischio del primo risultato."],
  ["Denaro e risorse","Davanti a un acquisto importante decide rapidamente se lo considera utile alla prossima sfida; confrontare per settimane ogni dettaglio gli sembra più costoso dell’eventuale errore."],
  ["Viaggio e imprevisti","Quando perde una coincidenza non resta a discutere sul programma fallito: individua subito un percorso alternativo e trascina gli altri verso il primo mezzo disponibile."],
  ["Amicizie e gruppi","Se gli amici esitano su cosa fare, lancia una proposta netta e comincia a organizzare; preferisce ricevere un no diretto piuttosto che una lunga serie di forse."],
  ["Confini personali","Quando sente invaso il proprio spazio reagisce nell’istante, chiarisce il limite senza molti giri di parole e torna sereno più velocemente di chi ha subito il confronto."],
  ["Apprendimento","Davanti a uno strumento nuovo salta parte delle istruzioni, prova subito i comandi principali e impara dagli errori prodotti durante l’azione."],
  ["Scelte difficili","Se due strade sono entrambe rischiose sceglie quella che gli permette di agire personalmente, perché tollera meglio una sconfitta combattuta che un’attesa passiva."],
  ["Creatività","Parte da un’idea energica, ne costruisce in fretta una prima versione e usa la reazione immediata degli altri per capire come migliorarla."],
  ["Cambiamento","Accoglie con entusiasmo un nuovo inizio finché può imprimergli una direzione propria; diventa impaziente se il passaggio resta soltanto teorico."],
  ["Fallimento e recupero","Dopo una sconfitta attraversa un momento acceso, poi cerca quasi subito una rivincita concreta con cui dimostrare a sé stesso di essere ancora capace." ]
 ],
 Toro:[
  ["Lavoro e responsabilità","Quando il gruppo cambia metodo all’ultimo momento chiede prove concrete del vantaggio, protegge il lavoro già affidabile e accetta la novità soltanto dopo una verifica pratica."],
  ["Denaro e risorse","Prima di spendere valuta durata, materiali e utilità quotidiana; preferisce pagare di più una volta sola piuttosto che sostituire continuamente qualcosa di fragile."],
  ["Viaggio e imprevisti","Se una prenotazione salta cerca una soluzione comoda e sicura, conserva ciò che del piano può essere salvato e rifiuta di trasformare il disagio in una corsa caotica."],
  ["Amicizie e gruppi","Non è sempre il primo a confidarsi, ma diventa la presenza che mantiene gli appuntamenti, ricorda i gusti degli altri e offre un luogo stabile in cui ritrovarsi."],
  ["Confini personali","Sopporta a lungo piccole pressioni senza reagire; quando però stabilisce che un limite è stato superato, farlo cambiare posizione richiede tempo e fatti solidi."],
  ["Apprendimento","Assimila una procedura ripetendola con calma finché il gesto diventa naturale, e diffida delle scorciatoie che promettono velocità senza basi consistenti."],
  ["Scelte difficili","Fra una possibilità brillante ma incerta e una meno appariscente ma sostenibile sceglie spesso quella che può proteggere e far crescere nel tempo."],
  ["Creatività","Costruisce attraverso consistenza, suono, gusto e materiali; continua a rifinire l’opera finché produce una sensazione concreta di equilibrio e pienezza."],
  ["Cambiamento","Ha bisogno di avvicinarsi alla novità per gradi, provarla nel quotidiano e verificare che non distrugga inutilmente la sicurezza conquistata."],
  ["Fallimento e recupero","Dopo un errore torna alle abitudini che lo tengono saldo, ricostruisce lentamente le risorse e riparte solo quando sente di avere di nuovo terreno sotto i piedi."]
 ],
 Gemelli:[
  ["Lavoro e responsabilità","Quando un progetto ristagna apre conversazioni con reparti diversi, raccoglie frammenti di informazione e trova una connessione che cambia il modo di leggere il problema."],
  ["Denaro e risorse","Può spendere volentieri per corsi, strumenti o brevi esperienze che alimentano una curiosità, ma perde interesse negli acquisti legati a un’unica routine immutabile."],
  ["Viaggio e imprevisti","Se cambia il programma consulta rapidamente mappe, messaggi e persone del posto, trasformando il contrattempo in una serie di possibilità da confrontare."],
  ["Amicizie e gruppi","Passa con naturalezza tra gruppi diversi, cambia registro senza sentirsi incoerente e spesso porta a ciascuno una notizia raccolta altrove."],
  ["Confini personali","Quando una conversazione diventa troppo intensa può alleggerirla con una battuta o spostarla su un altro piano, cercando spazio attraverso il movimento mentale."],
  ["Apprendimento","Ricorda meglio quando può fare domande, spiegare il concetto a qualcun altro e collegarlo a esempi lontani invece di ripeterlo nello stesso modo."],
  ["Scelte difficili","Prima di decidere costruisce più versioni plausibili della storia e può continuare ad aggiungere alternative anche quando gli altri vorrebbero già una risposta definitiva."],
  ["Creatività","Combina parole, riferimenti e idee nate in contesti diversi; la prima intuizione spesso arriva da un collegamento che agli altri sembrava soltanto una deviazione."],
  ["Cambiamento","Davanti a una nuova situazione modifica rapidamente linguaggio e strategia, ma deve impegnarsi per non abbandonare il percorso quando la fase di scoperta finisce."],
  ["Fallimento e recupero","Dopo un errore ne parla, lo ricostruisce da più punti di vista e recupera energia quando riesce a trasformarlo in una spiegazione o in un racconto utile."]
 ],
 Cancro:[
  ["Lavoro e responsabilità","Prima di modificare l’organizzazione osserva chi rischia di sentirsi escluso, conserva la memoria di ciò che ha già ferito il gruppo e propone un passaggio più protetto."],
  ["Denaro e risorse","Considera importante ciò che rende sicura la casa o aiuta una persona cara; un oggetto legato a un ricordo può avere per lui più valore del suo prezzo."],
  ["Viaggio e imprevisti","Quando il piano salta controlla innanzitutto come stanno le persone con lui, cerca un punto riparato e ricostruisce il percorso partendo dai bisogni del gruppo."],
  ["Amicizie e gruppi","All’inizio osserva le dinamiche senza esporsi troppo, poi crea una cerchia in cui ricorda dettagli personali e nota immediatamente ogni cambiamento d’umore."],
  ["Confini personali","Se non si sente al sicuro si ritrae, comunica molto attraverso il tono e concede di nuovo accesso soltanto quando percepisce attenzione autentica."],
  ["Apprendimento","Collega le informazioni a storie, luoghi e sensazioni; ciò che possiede un significato emotivo resta nella memoria molto più di una sequenza impersonale."],
  ["Scelte difficili","Valuta una decisione immaginando come cambierà la vita delle persone vicine e può rinunciare a un vantaggio personale per proteggere un legame fragile."],
  ["Creatività","Lavora con immagini intime, memorie e atmosfere; spesso costruisce qualcosa che fa sentire gli altri riconosciuti senza dichiararne apertamente il motivo."],
  ["Cambiamento","Accetta il nuovo quando riesce a portare con sé una continuità affettiva; un taglio improvviso con il passato gli richiede molto più tempo per essere elaborato."],
  ["Fallimento e recupero","Dopo una delusione si raccoglie in uno spazio familiare, ripercorre ciò che è accaduto e ricomincia quando torna a percepire una base emotiva affidabile."]
 ],
 Leone:[
  ["Lavoro e responsabilità","Se il gruppo perde entusiasmo rende visibile l’obiettivo, distribuisce riconoscimenti e si espone in prima persona, desiderando però che il proprio contributo non venga cancellato."],
  ["Denaro e risorse","Spende volentieri per un gesto memorabile o per qualcosa che rappresenti bene chi è; tollera meno un acquisto anonimo che non racconta alcuna storia."],
  ["Viaggio e imprevisti","Quando un evento salta prova a creare un’alternativa capace di salvare l’atmosfera, assumendo il ruolo di chi impedisce alla giornata di diventare insignificante."],
  ["Amicizie e gruppi","Incoraggia apertamente chi considera parte della propria cerchia, celebra i suoi successi e soffre se la stessa lealtà non viene mostrata nei suoi confronti."],
  ["Confini personali","Può accettare una critica severa se viene espressa con rispetto e in privato; reagisce invece con forza quando percepisce un tentativo pubblico di umiliarlo."],
  ["Apprendimento","Impara bene quando può trasformare la competenza in un’espressione personale, presentarla agli altri e ricevere una risposta viva sul risultato."],
  ["Scelte difficili","Davanti a una decisione impopolare preferisce dichiarare apertamente ciò in cui crede, purché possa conservarne la responsabilità e la dignità."],
  ["Creatività","Non si limita a completare il compito: cerca un elemento riconoscibile, un momento forte o una firma che renda il risultato impossibile da confondere con un altro."],
  ["Cambiamento","Accoglie una trasformazione se può viverla come crescita e conquista; fatica di più quando sembra ridurre il suo spazio o renderlo intercambiabile."],
  ["Fallimento e recupero","Dopo un colpo all’orgoglio recupera creando un risultato di cui possa tornare fiero e usando il calore delle persone leali come conferma, non come sostituto."]
 ],
 Vergine:[
  ["Lavoro e responsabilità","Quando riceve un incarico confuso ricostruisce i passaggi, individua le eccezioni e prepara una procedura che permetta anche agli altri di evitare lo stesso errore."],
  ["Denaro e risorse","Confronta costi, utilizzo e manutenzione, controllando anche i dettagli che molti ignorano; spende più serenamente quando può dimostrare la funzione concreta della scelta."],
  ["Viaggio e imprevisti","Di fronte a una cancellazione consulta orari, condizioni e alternative, prepara un piccolo elenco operativo e riduce il problema in azioni verificabili."],
  ["Amicizie e gruppi","Aiuta ricordando scadenze, correggendo un dettaglio o anticipando un bisogno pratico; talvolta gli altri scambiano questa attenzione per semplice critica."],
  ["Confini personali","Quando le richieste diventano troppe non esplode subito: aumenta il controllo, restringe la disponibilità e spiega con precisione quale parte non può più sostenere."],
  ["Apprendimento","Scompone il materiale in unità, verifica ogni passaggio con esempi e torna sui punti deboli finché il metodo produce risultati ripetibili."],
  ["Scelte difficili","Cerca la soluzione con meno conseguenze trascurate, anche se richiede più lavoro; una risposta elegante ma non verificabile continua a lasciarlo inquieto."],
  ["Creatività","La sua invenzione nasce spesso da una correzione: nota ciò che spreca tempo o funziona male e lo trasforma in una forma più pulita e utile."],
  ["Cambiamento","Si adatta meglio di quanto sembri quando può studiare il nuovo sistema, comprenderne le regole e migliorarlo attraverso piccoli interventi successivi."],
  ["Fallimento e recupero","Dopo un errore ripercorre ogni fase, distingue la causa dalla colpa e costruisce un controllo aggiuntivo prima di concedersi di considerare chiuso l’episodio."]
 ],
 Bilancia:[
  ["Lavoro e responsabilità","Quando due persone difendono proposte incompatibili, riformula entrambe senza svalutarle e cerca un criterio condiviso che permetta al gruppo di scegliere."],
  ["Denaro e risorse","Valuta non solo l’utilità ma anche proporzione, qualità e armonia con ciò che possiede; spesso preferisce decidere dopo aver ascoltato un’opinione di cui si fida."],
  ["Viaggio e imprevisti","Se il programma cambia prova a salvare l’esperienza di tutti, confronta desideri diversi e cerca un’alternativa che nessuno viva come una sconfitta completa."],
  ["Amicizie e gruppi","Nota chi monopolizza la conversazione e chi non trova spazio, intervenendo con tatto per riequilibrare la scena senza trasformarla in uno scontro."],
  ["Confini personali","Può rimandare un no per non spezzare l’armonia, ma quando la reciprocità manca troppo a lungo comincia a ridisegnare con decisione le distanze."],
  ["Apprendimento","Comprende un tema confrontando interpretazioni opposte e discutendone con qualcuno; la qualità del dialogo influenza molto la qualità del suo pensiero."],
  ["Scelte difficili","Prima di decidere immagina l’effetto su ogni parte coinvolta, e proprio la capacità di vedere entrambi i lati può rallentare il momento del verdetto."],
  ["Creatività","Lavora sulle relazioni tra forme, persone o idee, cercando una tensione equilibrata in cui nessun elemento cancelli completamente l’altro."],
  ["Cambiamento","Accetta il nuovo quando può negoziarne il passaggio e conservarne una forma armonica; reagisce male a chi impone senza spiegare né ascoltare."],
  ["Fallimento e recupero","Dopo un conflitto cerca di comprendere dove si sia spezzata la reciprocità, poi prova a riparare senza rinunciare alla propria dignità."]
 ],
 Scorpione:[
  ["Lavoro e responsabilità","Davanti a un problema delicato limita le confidenze, raccoglie contraddizioni e concentra le risorse sul punto nascosto che considera davvero decisivo."],
  ["Denaro e risorse","Non mostra facilmente tutte le proprie disponibilità, preferisce conservare margini di controllo e investe con convinzione quando intravede una trasformazione profonda."],
  ["Viaggio e imprevisti","Se qualcosa non torna osserva chi sa più di quanto dica, verifica dettagli in silenzio e prepara un’alternativa prima di mostrare quanto ha compreso."],
  ["Amicizie e gruppi","Concede fiducia per strati e ricorda come ciascuno ha gestito le informazioni più vulnerabili; poche prove di lealtà valgono più di molte presenze superficiali."],
  ["Confini personali","Protegge con decisione ciò che considera intimo e può chiudere completamente un accesso se percepisce manipolazione, anche senza spiegare subito la propria mossa."],
  ["Apprendimento","Non si accontenta della spiegazione ufficiale: segue cause, interessi e conseguenze finché raggiunge il meccanismo che gli altri preferivano non guardare."],
  ["Scelte difficili","Può attraversare una soluzione dolorosa se la considera autentica, mentre rifiuta compromessi che mantengono in vita un problema soltanto per renderlo meno visibile."],
  ["Creatività","Lavora con tensioni, simboli e parti rimosse, trasformando materiale difficile in qualcosa che costringe chi osserva a cambiare prospettiva."],
  ["Cambiamento","Quando decide di cambiare taglia i legami con la vecchia struttura e ricostruisce dalle fondamenta, invece di limitarsi a modificare l’apparenza."],
  ["Fallimento e recupero","Dopo una perdita attraversa fino in fondo la parte più dura, protegge il processo dagli sguardi esterni e riemerge con una strategia diversa e più controllata."]
 ],
 Sagittario:[
  ["Lavoro e responsabilità","Quando il gruppo si perde nei dettagli ricorda la direzione generale, propone un obiettivo più ampio e riaccende il movimento, anche rischiando di sottostimare i passaggi intermedi."],
  ["Denaro e risorse","Spende più facilmente per viaggi, formazione o esperienze che ampliano l’orizzonte; fatica a motivarsi per accumulare senza una prospettiva futura."],
  ["Viaggio e imprevisti","Una deviazione può entusiasmarlo quanto il programma originale: cerca cosa sia possibile scoprire lungo la nuova strada e comunica agli altri fiducia nel percorso."],
  ["Amicizie e gruppi","Coinvolge persone diverse attraverso racconti, ironia e progetti futuri, ma ha bisogno che il legame non diventi un controllo continuo dei suoi movimenti."],
  ["Confini personali","Quando si sente trattenuto dichiara apertamente il bisogno di spazio e può usare una sincerità più brusca di quanto la situazione richieda."],
  ["Apprendimento","Memorizza meglio quando comprende la visione complessiva, collega il tema a culture o discipline lontane e può discuterne il significato."],
  ["Scelte difficili","Tra una sicurezza chiusa e una possibilità incerta sceglie spesso la seconda se intravede crescita, esperienza o una verità più ampia da seguire."],
  ["Creatività","Parte da un’immagine grande e piena di possibilità, unisce riferimenti lontani e solo in seguito affronta la fatica di renderla realizzabile."],
  ["Cambiamento","Reagisce alla trasformazione cercandone subito il potenziale; la difficoltà arriva quando il nuovo richiede manutenzione quotidiana e non più esplorazione."],
  ["Fallimento e recupero","Dopo una caduta cerca il significato dell’esperienza, costruisce una nuova prospettiva e riparte quando riesce a vedere di nuovo una strada davanti a sé."]
 ],
 Capricorno:[
  ["Lavoro e responsabilità","Quando un progetto è in ritardo riduce le promesse, ridefinisce le tappe e prende sulle proprie spalle la parte più difficile per proteggere credibilità e risultato."],
  ["Denaro e risorse","Considera il denaro uno strumento di autonomia e stabilità futura, controlla la sostenibilità delle scelte e rinuncia senza drammi a ciò che indebolisce il piano."],
  ["Viaggio e imprevisti","Se una coincidenza salta verifica tempi e responsabilità, sceglie l’alternativa più affidabile e conserva energia invece di reagire in modo spettacolare."],
  ["Amicizie e gruppi","All’inizio appare riservato, ma dimostra appartenenza presentandosi nei momenti decisivi e mantenendo impegni che altri avevano preso con leggerezza."],
  ["Confini personali","Definisce i limiti attraverso disponibilità, ruoli e conseguenze concrete; quando ritira la fiducia è difficile recuperarla soltanto con le parole."],
  ["Apprendimento","Costruisce competenza per livelli, accetta di partire dal basso e continua finché può dimostrare il risultato in una situazione reale."],
  ["Scelte difficili","Valuta quale opzione potrà ancora sostenere fra anni, anche se nel presente appare meno gratificante o richiede una rinuncia che nessuno applaudirà."],
  ["Creatività","Dà forma alle idee imponendo struttura, limiti e scadenze; ciò che produce tende a essere sobrio, resistente e pensato per superare la prova del tempo."],
  ["Cambiamento","Non rifiuta necessariamente la trasformazione, ma vuole capire quale struttura sostituirà la precedente e chi ne sosterrà davvero il costo."],
  ["Fallimento e recupero","Dopo un insuccesso riduce l’esposizione, studia la gerarchia degli errori e ricomincia da una posizione più bassa senza perdere la meta finale."]
 ],
 Acquario:[
  ["Lavoro e responsabilità","Quando una procedura crea sempre lo stesso problema smette di correggere i singoli casi, mette in discussione la regola e progetta un sistema alternativo per tutti."],
  ["Denaro e risorse","È disposto a investire in tecnologia, reti o idee non convenzionali se ne vede l’utilità collettiva, mentre attribuisce poco valore allo status tradizionale."],
  ["Viaggio e imprevisti","Davanti a un blocco consulta reti, strumenti e possibilità insolite, osservando il problema come una struttura da aggirare più che come un dramma personale."],
  ["Amicizie e gruppi","Si muove bene fra persone molto diverse quando condividono un’idea, difendendo il diritto di ciascuno a restare autonomo dentro il gruppo."],
  ["Confini personali","Può offrire molto sul piano mentale e collettivo, ma protegge uno spazio indipendente in cui non vuole dover spiegare ogni distanza emotiva."],
  ["Apprendimento","Comprende cercando schemi, eccezioni e implicazioni future; una regola lo interessa soprattutto quando può verificarne i limiti o immaginarne una migliore."],
  ["Scelte difficili","Se consuetudine e principio entrano in conflitto può rompere con il modo abituale, anche a costo di apparire freddo o imprevedibile agli occhi degli altri."],
  ["Creatività","Combina visione sistemica e deviazione, costruendo soluzioni che all’inizio sembrano strane ma aprono possibilità utilizzabili da molte persone."],
  ["Cambiamento","Paradossalmente resiste quando qualcuno vuole modificare i suoi principi, ma rivoluziona senza esitazione strutture che considera diventate obsolete."],
  ["Fallimento e recupero","Dopo un errore prende distanza dall’emozione, cerca il difetto del sistema e recupera quando può trasformare il caso individuale in un modello migliore."]
 ],
 Pesci:[
  ["Lavoro e responsabilità","In un gruppo teso percepisce ciò che nessuno esprime, adatta il proprio contributo al clima e trova una forma capace di tenere insieme bisogni apparentemente incompatibili."],
  ["Denaro e risorse","Può attribuire più importanza al significato, alla bellezza o all’aiuto offerto che al calcolo preciso, e deve fermarsi per distinguere generosità da dispersione."],
  ["Viaggio e imprevisti","Quando il programma salta segue segnali, atmosfere e intuizioni, trasformando la deviazione in esperienza; rischia però di trascurare un dettaglio pratico decisivo."],
  ["Amicizie e gruppi","Ascolta senza imporre subito una soluzione, assume facilmente il tono emotivo degli altri e deve ritrovare da solo la differenza tra empatia e assorbimento."],
  ["Confini personali","Può lasciare i limiti sfumati per non ferire, finché la stanchezza lo porta a sparire o rifugiarsi in uno spazio che gli altri non riescono più a raggiungere."],
  ["Apprendimento","Comprende attraverso immagini, associazioni e intuizioni che maturano lentamente; spesso sa dove conduce un tema prima di riuscire a spiegarne i passaggi."],
  ["Scelte difficili","Immagina il dolore e le ragioni di tutte le persone coinvolte, rischiando di rimandare il confine necessario pur di non ridurre nessuno a un giudizio semplice."],
  ["Creatività","Lascia che musica, sogno e impressioni si mescolino finché emerge una forma capace di dire qualcosa che un ragionamento lineare non avrebbe raggiunto."],
  ["Cambiamento","Si adatta quasi senza attrito all’ambiente nuovo e proprio per questo deve chiedersi se la direzione scelta appartenga davvero a lui o al clima circostante."],
  ["Fallimento e recupero","Dopo una delusione si ritira nell’immaginazione, nell’arte o nella vicinanza silenziosa, poi ritorna quando il dolore ha trovato un significato più ampio."]
 ]
};
