const portraits={
 Ariete:[
  ["Durante un progetto nuovo apre subito un documento, assegna i primi compiti e prova una soluzione ancora prima che gli altri abbiano finito di discutere.","Se il gruppo esita davanti a un’attività sconosciuta, si offre per iniziare e preferisce correggere la rotta in corsa.","Trasforma facilmente una commissione o un allenamento in una piccola gara con sé stesso e punta a battere il risultato precedente."],
  ["Quando nasce un litigio dice immediatamente cosa non va, alza il tono per un momento e poco dopo propone di ricominciare da zero.","Per coinvolgere una persona non prepara lunghi discorsi: lancia una proposta diretta e si aspetta una risposta altrettanto chiara.","Se qualcuno viene trattato ingiustamente interviene d’istinto, anche quando sarebbe più prudente capire prima tutta la situazione."],
  ["Sotto pressione accelera, decide con poche informazioni e preferisce rischiare un errore piuttosto che restare immobile.","Quando un ostacolo blocca il gruppo tenta di sfondarlo frontalmente; l’attesa e i passaggi burocratici lo innervosiscono più della fatica.","In emergenza prende il posto davanti, reagisce in fretta e solo dopo si rende conto di quanto fosse teso."],
  ["Dopo aver conquistato un obiettivo perde interesse se non compare subito una nuova sfida da avviare.","Rende al massimo quando può essere il primo a tentare, aprire una strada o difendere apertamente una posizione.","La sua energia aumenta davanti a una sfida immediata e diminuisce nei lavori che richiedono lente revisioni senza un traguardo visibile."]
 ],
 Toro:[
  ["Prima di cambiare un’abitudine verifica che la nuova soluzione sia davvero più comoda, affidabile e sostenibile nel tempo.","In casa sistema gli oggetti in modo preciso, compra poche cose ma vuole sentirne la qualità e continua a usare ciò che funziona.","Affronta un compito con ritmo costante, fa pause regolari e preferisce completare bene una fase prima di aprirne un’altra."],
  ["Dimostra affetto ricordandosi cosa piace all’altra persona, preparando qualcosa di concreto o rendendo più confortevole un momento insieme.","Quando una relazione attraversa una difficoltà non fugge facilmente: resta, osserva i fatti e prova a ricostruire la sicurezza poco alla volta.","Se una promessa viene mantenuta per mesi si fida sempre di più; una bella dichiarazione senza continuità lo convince poco."],
  ["Sotto pressione rallenta le decisioni, protegge ciò che è già stabile e rifiuta cambiamenti imposti all’ultimo minuto.","Durante un conflitto parla poco ma non sposta la propria posizione finché non riceve prove molto concrete.","In una crisi si concentra sulle risorse disponibili, sui bisogni fisici e su ciò che può essere reso di nuovo prevedibile."],
  ["Può sopportare un lavoro lungo più di molti altri, ma reagisce male quando qualcuno tenta di trascinarlo senza preavviso.","Il suo sì arriva lentamente, però una volta dato diventa difficile farlo tornare indietro.","Costruisce benessere attraverso continuità, contatto con ciò che è tangibile e risultati che si possono conservare."]
 ],
 Gemelli:[
  ["Mentre cerca una risposta apre più conversazioni, confronta versioni diverse e finisce per scoprire collegamenti che nessuno aveva notato.","In una giornata libera alterna messaggi, brevi spostamenti e curiosità nuove; stare troppo a lungo sullo stesso tema lo spegne.","Impara meglio spiegando ad alta voce, facendo domande veloci e cambiando esempio finché l’idea non diventa chiara."],
  ["Quando conosce qualcuno esplora molti argomenti, osserva come reagisce alle parole e adatta rapidamente il tono della conversazione.","In un gruppo collega persone che hanno informazioni diverse e spesso diventa il punto attraverso cui passano le novità.","Dopo un litigio sente il bisogno di parlarne da più angolazioni; il silenzio prolungato gli pesa più di una discussione vivace."],
  ["Sotto pressione raccoglie notizie, formula scenari alternativi e può saltare da una possibilità all’altra senza fermarsi.","Se un piano crolla inventa rapidamente una variante, ma rischia di abbandonarla appena ne appare una più interessante.","In emergenza mantiene la mente mobile e comunica molto; la difficoltà è scegliere quale delle molte piste seguire fino in fondo."],
  ["La sua attenzione si riaccende quando c’è qualcosa da tradurre, collegare, raccontare o osservare da un punto di vista nuovo.","Può sostenere due idee opposte per verificarne la logica e non considera il cambio di opinione una sconfitta.","Dà il meglio quando informazioni, persone e possibilità circolano; la ripetizione priva di scoperta lo rende irrequieto."]
 ],
 Cancro:[
  ["Entrando in un ambiente nuovo nota subito chi è a disagio, chi è rimasto escluso e quali dettagli potrebbero far sentire tutti più a casa.","Conserva messaggi, fotografie e piccoli oggetti perché li usa come porte d’accesso a momenti precisi della propria storia.","Organizza la giornata tenendo conto dell’umore delle persone vicine e modifica i piani se percepisce che qualcuno ha bisogno di protezione."],
  ["Mostra affetto ricordando abitudini intime, preparando uno spazio sicuro e facendo domande che permettono all’altro di abbassare le difese.","Se si sente ferito può ritirarsi senza spiegare tutto, aspettando che l’altra persona capisca dal cambiamento di atmosfera.","In un gruppo tende a creare un nucleo ristretto di fiducia e difende con forza chi considera parte della propria cerchia."],
  ["Sotto pressione cerca un luogo familiare, ripercorre precedenti esperienze e reagisce molto al clima emotivo che lo circonda.","Durante un conflitto ricorda non solo le parole appena dette ma anche episodi lontani che avevano prodotto la stessa sensazione.","In emergenza si occupa prima delle persone vulnerabili, poi elabora in privato la paura che non aveva mostrato."],
  ["Le sue decisioni più importanti passano attraverso una domanda silenziosa: qui potrò sentirmi al sicuro e proteggere ciò a cui tengo?","Avanza e si ritrae come se misurasse continuamente la distanza emotiva; quando si fida, la memoria del legame diventa potentissima.","Il suo istinto non cerca il centro della scena ma un luogo da custodire, con persone e ricordi che abbiano continuità."]
 ],
 Leone:[
  ["Quando presenta un lavoro cura il momento in cui verrà mostrato, vuole che abbia una firma riconoscibile e osserva con attenzione la reazione degli altri.","In una festa tende a riunire le persone, inventa un gesto memorabile e si assicura che nessuno viva una serata completamente anonima.","Se crede in un’idea le dà forma con entusiasmo visibile e preferisce assumersene apertamente la responsabilità."],
  ["Dimostra affetto con gesti generosi e personali; desidera che l’altra persona riconosca il significato speciale di ciò che ha fatto.","Nel gruppo incoraggia chi è insicuro, ma soffre quando il proprio contributo viene ignorato o trattato come intercambiabile.","In un litigio difende la propria dignità con forza; una critica privata e leale viene accolta meglio di una svalutazione davanti agli altri."],
  ["Sotto pressione raddrizza la postura, prova a mantenere il controllo della scena e nasconde più facilmente la vulnerabilità che la rabbia.","Se il gruppo perde fiducia, crea un obiettivo simbolico e usa la propria sicurezza per riaccendere l’energia comune.","Quando fallisce teme soprattutto che l’errore definisca il suo valore; recupera creando qualcosa di cui possa tornare fiero."],
  ["Ha bisogno di sentire che ciò che offre porta una traccia personale, non soltanto che il compito è stato eseguito correttamente.","Rende al massimo quando può esprimere coraggio, creatività e presenza senza dover fingere di essere invisibile.","Non cerca soltanto attenzione: cerca una risposta viva che confermi che il calore investito è arrivato davvero a qualcuno."]
 ],
 Vergine:[
  ["Prima di consegnare un lavoro controlla nomi, passaggi e incoerenze, poi crea una piccola procedura per evitare che l’errore ritorni.","Quando entra in una situazione confusa individua subito cosa manca, cosa è fuori posto e quale intervento concreto migliorerebbe il risultato.","Impara scomponendo il problema in parti verificabili e prova soddisfazione quando un metodo diventa più preciso ed efficiente."],
  ["Mostra affetto risolvendo inconvenienti, ricordando dettagli pratici e anticipando bisogni che l’altra persona non aveva espresso chiaramente.","In una relazione osserva attentamente le abitudini; può sembrare critica proprio nei momenti in cui sta cercando di rendersi utile.","Preferisce una conversazione onesta e specifica a grandi promesse: vuole sapere cosa cambierà concretamente da domani."],
  ["Sotto pressione aumenta i controlli, vede ogni imperfezione e rischia di dedicare troppe energie a un dettaglio secondario.","In emergenza prepara elenchi, distribuisce compiti e cerca la causa esatta invece di affidarsi a una rassicurazione generica.","Se qualcosa va male ripercorre mentalmente tutti i passaggi per capire dove avrebbe potuto prevenirlo."],
  ["Il suo talento emerge quando può trasformare attenzione minuziosa in un miglioramento realmente utile per qualcuno.","Non vuole soltanto che una soluzione sembri buona: vuole che regga alla prova dei fatti, dei dettagli e delle conseguenze.","Può faticare a considerare concluso un lavoro perché vede sempre l’ultimo margine di correzione che gli altri non notano."]
 ],
 Bilancia:[
  ["Davanti a due proposte ascolta entrambe, riformula i punti validi e cerca una soluzione che nessuno percepisca come un’umiliazione.","Cura il modo in cui persone, parole e oggetti stanno insieme; un ambiente disarmonico gli distrae anche quando è funzionale.","Prima di scegliere immagina come ogni alternativa cambierà gli equilibri e spesso chiede un confronto per vedere ciò che gli sfugge."],
  ["In una relazione presta attenzione alla reciprocità dei gesti e prova a creare occasioni in cui entrambi possano riconoscersi.","Durante un litigio abbassa i toni, cerca la frase più giusta e può rimandare il momento di dichiarare una preferenza netta.","Nel gruppo nota rapidamente alleanze e tensioni; spesso avvicina due persone trovando un terreno che possano condividere."],
  ["Sotto pressione continua a confrontare pro e contro e rischia di perdere tempo nel tentativo di non danneggiare nessuna parte.","Quando l’atmosfera diventa aggressiva lavora sul tono e sulla forma prima ancora che sul contenuto del problema.","In emergenza cerca una seconda opinione affidabile; decidere da solo gli pesa soprattutto quando la scelta avrà conseguenze sugli altri."],
  ["La sua efficacia cresce quando può negoziare differenze reali senza rinunciare né alla giustizia né alla qualità della relazione.","Vede con facilità il lato che manca in un discorso, ma proprio questa capacità può rendere difficile pronunciare un verdetto definitivo.","Non evita ogni conflitto: tenta di trasformarlo in un accordo che conservi dignità, proporzione e possibilità di dialogo."]
 ],
 Scorpione:[
  ["In una conversazione ascolta le pause, nota ciò che viene evitato e torna con una domanda precisa sul punto che gli altri avevano lasciato nascosto.","Quando decide di capire un problema scende fino alla causa, anche se il percorso costringe a guardare informazioni scomode.","Condivide poco alla volta ciò che considera davvero importante e osserva come l’altra persona gestisce ogni livello di fiducia."],
  ["In una relazione cerca lealtà profonda e coerenza nei momenti difficili; i gesti superficiali non compensano una fiducia tradita.","Durante un conflitto non dimentica facilmente il punto vulnerabile scoperto, ma evita di mostrarlo finché non decide come usarlo.","Protegge la propria intimità e quella di chi ama; preferisce pochi legami intensi a molte presenze senza profondità."],
  ["Sotto pressione riduce le parole, concentra l’attenzione e prova a recuperare controllo su ciò che nessuno vede.","In una crisi attraversa la parte più difficile senza fingere che sia leggera, poi cerca il modo di trasformare la perdita in nuova forza.","Se sospetta un inganno verifica silenziosamente dettagli e contraddizioni prima di rivelare quanto ha compreso."],
  ["Il suo modo di cambiare non è cosmetico: tende a chiudere un ciclo, eliminare ciò che non regge e ricostruire dalle fondamenta.","Possiede una resistenza particolare nei passaggi estremi, ma può confondere la protezione con il controllo assoluto.","Dà il meglio quando una situazione richiede coraggio emotivo, strategia e capacità di restare presente dove altri distolgono lo sguardo."]
 ],
 Sagittario:[
  ["Davanti a un argomento nuovo cerca subito il quadro generale, collega l’idea a esperienze lontane e immagina dove potrebbe condurre.","Programma un viaggio lasciando spazi aperti, perché considera gli imprevisti parte dell’esperienza e non soltanto un difetto del piano.","In una discussione porta esempi, principi e scenari futuri; i dettagli lo interessano soprattutto se sostengono un significato più ampio."],
  ["Con le persone è diretto, scherza facilmente e propone esperienze condivise invece di lunghe verifiche reciproche.","Durante un litigio dice una verità in modo brusco, poi resta sorpreso se l’intenzione sincera non basta a cancellare l’effetto delle parole.","Ha bisogno che un legame lasci spazio a esplorazione, crescita e autonomia; interpreta il controllo continuo come mancanza di fiducia."],
  ["Sotto pressione cerca una via d’uscita, amplia l’orizzonte e si aggrappa alla possibilità che l’esperienza abbia un senso futuro.","Se un piano fallisce ne costruisce uno più grande, ma può sottovalutare i passaggi pratici necessari a realizzarlo.","In emergenza trasmette fiducia e movimento; il rischio è promettere una soluzione prima di averne misurato davvero i limiti."],
  ["La sua energia aumenta quando può attraversare confini fisici o mentali e raccontare ciò che ha scoperto lungo il percorso.","Preferisce una verità scomoda a una prudenza che percepisce come ipocrisia, anche quando dovrebbe curare meglio il modo di dirla.","Non cerca solo novità: cerca una direzione capace di dare significato alle esperienze e di aprire una possibilità più ampia."]
 ],
 Capricorno:[
  ["Davanti a un obiettivo lungo costruisce tappe, valuta risorse e responsabilità e accetta di rinunciare a un piacere immediato per il risultato finale.","In un gruppo osserva chi mantiene davvero gli impegni e assegna fiducia sulla base della continuità, non dell’entusiasmo iniziale.","Prima di esporsi prepara una struttura solida; preferisce apparire prudente oggi piuttosto che perdere credibilità domani."],
  ["Dimostra affetto diventando affidabile nei momenti importanti, anche se non sempre racconta quanto gli costa esserlo.","Durante un litigio controlla le emozioni, torna ai fatti e può sembrare distante proprio quando teme di perdere il controllo.","In una relazione pensa alla durata, agli impegni concreti e a ciò che due persone saranno in grado di sostenere nel tempo."],
  ["Sotto pressione lavora di più, restringe le priorità e prova a trasformare l’ansia in disciplina.","In emergenza assume responsabilità che altri evitano, ma può trattare la propria stanchezza come un ostacolo da ignorare.","Se fallisce analizza la posizione, accetta una fase lenta e ricomincia da un gradino più basso pur di risalire con basi solide."],
  ["Misura il progresso in risultati accumulati e reputazione mantenuta; il riconoscimento ha valore se conferma una competenza reale.","Sa aspettare più di quanto sembri, purché ogni sacrificio appartenga a una costruzione con direzione e scadenze credibili.","La sua ambizione non è sempre rumorosa: spesso appare come il bisogno di diventare la persona su cui il sistema può reggersi."]
 ],
 Acquario:[
  ["Quando tutti usano lo stesso metodo domanda chi abbia deciso che debba funzionare così e prova a ridisegnare l’intero sistema.","In un gruppo mette in contatto persone molto diverse attorno a un’idea comune, senza pretendere che diventino simili.","Osserva un problema da una certa distanza, cerca schemi collettivi e propone una soluzione che potrebbe funzionare anche per chi non è presente."],
  ["In una relazione ha bisogno di amicizia, confronto mentale e libertà di conservare uno spazio non negoziabile tutto suo.","Durante un litigio può passare improvvisamente dalle emozioni al ragionamento generale, come se studiasse il caso dall’esterno.","Difende con forza il diritto di ciascuno a essere diverso, ma talvolta non si accorge che l’altra persona chiede vicinanza più che principi."],
  ["Sotto pressione si distacca, analizza la struttura e cerca una soluzione inattesa invece di ripetere ciò che ha già fallito.","In emergenza pensa alla rete, alle risorse condivise e agli effetti sul gruppo; può però sembrare freddo nel contatto individuale.","Se viene costretto ad adeguarsi senza spiegazioni diventa più oppositivo e investe energia nel dimostrare che esiste un’alternativa."],
  ["La sua firma emerge quando trasforma un’idea insolita in una possibilità utile a una comunità e non soltanto in eccentricità personale.","È fedele ai propri principi ma imprevedibile nelle forme; può cambiare tutto per restare coerente con una visione più profonda.","Dà il meglio nei problemi che richiedono indipendenza mentale, innovazione e capacità di immaginare regole non ancora esistenti."]
 ],
 Pesci:[
  ["Entrando in una stanza assorbe facilmente il tono emotivo e modifica il proprio comportamento prima ancora di capire cosa sia cambiato.","Quando crea qualcosa parte da immagini, musica o sensazioni e lascia che il significato emerga mentre lavora.","Davanti a una storia altrui immagina molte spiegazioni, sente il dolore dietro le parole e fatica a ridurlo a un giudizio semplice."],
  ["In una relazione offre ascolto e comprensione, ma può accettare troppo a lungo confini confusi per non ferire l’altra persona.","Durante un litigio percepisce ogni sfumatura del tono; se la situazione diventa dura può allontanarsi, fantasticare o dire ciò che ristabilisce pace.","Si lega anche attraverso silenzi, intuizioni e simboli condivisi; una connessione priva di sensibilità gli appare vuota."],
  ["Sotto pressione perde facilmente i confini tra il proprio problema e quello degli altri e ha bisogno di ritrovare uno spazio interiore.","In una crisi segue l’intuizione e sa stare accanto al dolore senza pretendere di risolverlo subito, ma rischia di dimenticare i limiti pratici.","Se la realtà diventa troppo rigida cerca rifugio nell’immaginazione, nell’arte o in una possibilità che nessun fatto ha ancora confermato."],
  ["La sua forza appare quando sensibilità e immaginazione diventano cura, arte o capacità di comprendere ciò che non viene detto.","Può adattarsi fino a sembrare persone diverse in ambienti diversi; il compito difficile è riconoscere quale desiderio appartenga davvero a lui.","Non procede sempre in linea retta: raccoglie segnali sottili, li lascia sedimentare e arriva a una risposta che sa spiegare soltanto dopo."]
 ]
};

export const portraitStageNames=["Vita quotidiana","Legami","Sotto pressione","Firma profonda"];

export function buildPortrait(name,rng=Math.random){
 const stages=portraits[name];
 if(!stages)throw new Error(`Profilo sconosciuto: ${name}`);
 return stages.map((variants,index)=>({stage:portraitStageNames[index],text:variants[Math.floor(rng()*variants.length)]}));
}

export function portraitVariantCount(){return Object.values(portraits).reduce((sum,stages)=>sum+stages.reduce((n,v)=>n+v.length,0),0)}

